from typing import Any, Callable, Optional

class App:
    def __init__(self, name: Optional[str] = None, help: Optional[str] = None, version: Optional[str] = None) -> None: ...
    def command(self) -> Callable[..., Any]: ...
    def group(self) -> Callable[..., Any]: ...
    def run(self) -> None: ...
