steps:
  - id: receiver
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - --tag=${_REGISTRY}/receiver:${_TAG}
      - benchmarks/gcp-managed-services/receiver

  - id: client
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - --tag=${_REGISTRY}/client:${_TAG}
      - benchmarks/gcp-managed-services/client

  - id: tape
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - --file=benchmarks/gcp-managed-services/images/Dockerfile.services
      - --target=tape
      - --tag=${_REGISTRY}/tape:${_TAG}
      - .

  - id: defer
    name: gcr.io/cloud-builders/docker
    waitFor: ["tape"]
    args:
      - build
      - --file=benchmarks/gcp-managed-services/images/Dockerfile.services
      - --target=defer
      - --tag=${_REGISTRY}/defer:${_TAG}
      - .

  - id: relay
    name: gcr.io/cloud-builders/docker
    waitFor: ["defer"]
    args:
      - build
      - --file=benchmarks/gcp-managed-services/images/Dockerfile.services
      - --target=relay
      - --tag=${_REGISTRY}/relay:${_TAG}
      - .

images:
  - ${_REGISTRY}/receiver:${_TAG}
  - ${_REGISTRY}/client:${_TAG}
  - ${_REGISTRY}/tape:${_TAG}
  - ${_REGISTRY}/defer:${_TAG}
  - ${_REGISTRY}/relay:${_TAG}

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
