// Code generated by jet codegen openapi. DO NOT EDIT.

import useSWR from "swr";
import type { SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";
import type { ApiClient } from "./client";
import type { CreatePetData, CreatePetResponse, GetPetByIdData, GetPetByIdResponse, ListPetsData, ListPetsResponse } from "./types";

export function createHooks(client: ApiClient) {
  return {
    useListPets(data: ListPetsData, config?: SWRConfiguration<ListPetsResponse>) {
      return useSWR<ListPetsResponse>(["listPets", data], () => client.listPets(data), config);
    },
    useCreatePet(config?: SWRMutationConfiguration<CreatePetResponse, Error, string, CreatePetData>) {
      return useSWRMutation<CreatePetResponse, Error, string, CreatePetData>("createPet", (_key, { arg }) => client.createPet(arg), config);
    },
    useGetPetById(data: GetPetByIdData, config?: SWRConfiguration<GetPetByIdResponse>) {
      return useSWR<GetPetByIdResponse>(["getPetById", data], () => client.getPetById(data), config);
    },
  };
}
