// Code generated by jet codegen openapi. DO NOT EDIT.

import type { ClientConfig } from "./runtime";
import { request } from "./runtime";
import type { CreatePetData, CreatePetResponse, GetPetByIdData, GetPetByIdResponse, ListPetsData, ListPetsResponse } from "./types";

export function createClient(config: ClientConfig) {
  return {
    listPets(data: ListPetsData): Promise<ListPetsResponse> {
      return request<ListPetsResponse>(config, { method: "GET", path: `/pets`, query: { limit: data.query?.limit } });
    },
    createPet(data: CreatePetData): Promise<CreatePetResponse> {
      return request<CreatePetResponse>(config, { method: "POST", path: `/pets`, body: data.body });
    },
    getPetById(data: GetPetByIdData): Promise<GetPetByIdResponse> {
      return request<GetPetByIdResponse>(config, { method: "GET", path: `/pets/${data.path.petId}` });
    },
  };
}

export type ApiClient = ReturnType<typeof createClient>;
