// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-snapshots-codegen-minimal-runtime-axios-ts" reason="Existing code claimed during Score standardization until deterministic generator coverage lands.">
// Code generated by jet codegen openapi. DO NOT EDIT.

import axios from "axios";
import type { AxiosInstance } from "axios";

export interface ClientConfig {
  baseUrl: string;
  axios?: AxiosInstance;
  headers?: Record<string, string>;
}

export interface RequestArgs {
  method: string;
  path: string;
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
}

export async function request<T>(config: ClientConfig, args: RequestArgs): Promise<T> {
  const instance = config.axios ?? axios.create();
  const response = await instance.request<T>({
    method: args.method,
    baseURL: config.baseUrl,
    url: args.path,
    params: args.query,
    data: args.body,
    headers: { "Content-Type": "application/json", ...config.headers, ...args.headers },
  });
  return response.data;
}

// </HANDWRITE>
