// Code generated by jet codegen openapi. DO NOT EDIT.

export interface NewPet {
  name: string;
  tag?: string;
}

export interface Pet {
  id: number;
  name: string;
  status?: "available" | "pending" | "sold";
  tag?: string;
}

