// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-snapshots-codegen-minimal-runtime-ts" reason="Existing code claimed during Score standardization until deterministic generator coverage lands.">
// Code generated by jet codegen openapi. DO NOT EDIT.

export interface ClientConfig {
  baseUrl: string;
  fetch?: typeof fetch;
  headers?: Record<string, string>;
}

export interface RequestArgs {
  method: string;
  path: string;
  query?: Record<string, unknown>;
  body?: unknown;
  headers?: Record<string, string>;
}

export async function request<T>(config: ClientConfig, args: RequestArgs): Promise<T> {
  const doFetch = config.fetch ?? fetch;
  const url = new URL(config.baseUrl + args.path);
  if (args.query) {
    for (const [key, value] of Object.entries(args.query)) {
      if (value !== undefined && value !== null) {
        url.searchParams.set(key, String(value));
      }
    }
  }
  const response = await doFetch(url.toString(), {
    method: args.method,
    headers: { "Content-Type": "application/json", ...config.headers, ...args.headers },
    body: args.body !== undefined ? JSON.stringify(args.body) : undefined,
  });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`);
  }
  if (response.status === 204) {
    return undefined as T;
  }
  return (await response.json()) as T;
}

// </HANDWRITE>
