// Code generated by jet codegen openapi. DO NOT EDIT.

import type { ClientConfig } from "./runtime";
import { request } from "./runtime";
import type { NewPet, Pet } from "./types";

export function createClient(config: ClientConfig) {
  return {
    listPets(params: { limit?: number }): Promise<Pet[]> {
      return request<Pet[]>(config, { method: "GET", path: `/pets`, query: { limit: params.limit } });
    },
    createPet(params: { body: NewPet }): Promise<Pet> {
      return request<Pet>(config, { method: "POST", path: `/pets`, body: params.body });
    },
    getPetById(params: { petId: number }): Promise<Pet> {
      return request<Pet>(config, { method: "GET", path: `/pets/${params.petId}` });
    },
  };
}

export type ApiClient = ReturnType<typeof createClient>;
