// Code generated by jet codegen openapi. DO NOT EDIT.

import { useMutation, useQuery } from "@tanstack/react-query";
import type { UseMutationOptions, UseQueryOptions } from "@tanstack/react-query";
import type { ApiClient } from "./client";
import type { NewPet, Pet } from "./types";

export function createHooks(client: ApiClient) {
  return {
    useListPetsQuery(params: { limit?: number }, options?: Omit<UseQueryOptions<Pet[]>, "queryKey" | "queryFn">) {
      return useQuery<Pet[]>({ queryKey: ["listPets", params], queryFn: () => client.listPets(params), ...options });
    },
    useCreatePetMutation(options?: UseMutationOptions<Pet, Error, { body: NewPet }>) {
      return useMutation<Pet, Error, { body: NewPet }>({ mutationFn: (variables) => client.createPet(variables), ...options });
    },
    useGetPetByIdQuery(params: { petId: number }, options?: Omit<UseQueryOptions<Pet>, "queryKey" | "queryFn">) {
      return useQuery<Pet>({ queryKey: ["getPetById", params], queryFn: () => client.getPetById(params), ...options });
    },
  };
}
