// Code generated by jet codegen openapi. DO NOT EDIT.

export interface NewPet {
  name: string;
  tag?: string;
}

export interface Pet {
  id: number;
  name: string;
  status?: "available" | "pending" | "sold";
  tag?: string;
}

export type ListPetsData = { query?: { limit?: number } };

export type ListPetsResponse = Pet[];

export type CreatePetData = { body: NewPet };

export type CreatePetResponse = Pet;

export type GetPetByIdData = { path: { petId: number } };

export type GetPetByIdResponse = Pet;

