// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-openapi-golden-rs" reason="Root EC wrapper delegates to the maintained codegen golden test module until deterministic generator coverage lands.">
// SPEC-MANAGED: generated by `aw ec gen` from EC claim `stack-aware-openapi-codegen` — fill the body.
// @ec stack-aware-openapi-codegen
// @capability rust-native-frontend-toolchain
#[path = "codegen/openapi_golden.rs"]
mod codegen_openapi_golden;

// </HANDWRITE>
