from typing import Any, Optional

class Series:
    def __init__(self, data: list[Any], name: Optional[str] = None) -> None: ...
    @property
    def name(self) -> Optional[str]: ...
    @name.setter
    def name(self, value: str) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def tolist(self) -> list[Any]: ...
    def sum(self) -> float: ...
    def mean(self) -> float: ...
    def min(self) -> Any: ...
    def max(self) -> Any: ...
    def std(self) -> float: ...
    def var(self) -> float: ...
    def median(self) -> float: ...
    def count(self) -> int: ...
    def unique(self) -> list[Any]: ...
    def sort_values(self, ascending: bool = True) -> Series: ...
    def fillna(self, value: Any) -> Series: ...
    def dropna(self) -> Series: ...
    def isna(self) -> list[bool]: ...
    def expanding(self) -> Expanding: ...
    def ewm(self, span: Optional[float] = None, alpha: Optional[float] = None, halflife: Optional[float] = None) -> Ewm: ...
    def rolling(self, window: int) -> Rolling: ...

class DataFrame:
    def __init__(self, data: dict[str, list[Any]]) -> None: ...
    @property
    def nrows(self) -> int: ...
    @property
    def ncols(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def columns(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Series: ...
    def __len__(self) -> int: ...
    def head(self, n: int = 5) -> DataFrame: ...
    def tail(self, n: int = 5) -> DataFrame: ...
    def describe(self) -> Any: ...
    def sort_values(self, by: str, ascending: bool = True) -> DataFrame: ...
    def dropna(self) -> DataFrame: ...
    def fillna(self, value: Any) -> DataFrame: ...
    def select(self, columns: list[str]) -> DataFrame: ...
    def drop_column(self, column: str) -> DataFrame: ...
    def to_dict(self) -> Any: ...
    def groupby(self, by: list[str]) -> GroupBy: ...
    def join(self, other: DataFrame, on: list[str], how: str = "inner") -> DataFrame: ...
    def merge(self, other: DataFrame, on: list[str], how: str = "inner") -> DataFrame: ...
    def to_csv(self, path: str, delimiter: str = ",", header: bool = True) -> None: ...
    def pivot_table(self, values: str, index: str, columns: str, aggfunc: str = "mean") -> DataFrame: ...
    def to_columnar(self, path: str) -> None: ...
    @staticmethod
    def from_columnar(path: str) -> DataFrame: ...

class GroupBy:
    @property
    def ngroups(self) -> int: ...
    def sum(self) -> DataFrame: ...
    def mean(self) -> DataFrame: ...
    def count(self) -> DataFrame: ...
    def min(self) -> DataFrame: ...
    def max(self) -> DataFrame: ...
    def first(self) -> DataFrame: ...
    def last(self) -> DataFrame: ...

class Expanding:
    def min_periods(self, min_periods: int) -> Expanding: ...
    def sum(self) -> Series: ...
    def mean(self) -> Series: ...
    def min(self) -> Series: ...
    def max(self) -> Series: ...
    def std(self) -> Series: ...
    def var(self) -> Series: ...

class Ewm:
    def min_periods(self, min_periods: int) -> Ewm: ...
    def adjust_flag(self, adjust: bool) -> Ewm: ...
    def mean(self) -> Series: ...
    def std(self) -> Series: ...
    def var(self) -> Series: ...

class Rolling:
    def sum(self) -> Series: ...
    def mean(self) -> Series: ...
    def min(self) -> Series: ...
    def max(self) -> Series: ...
    def std(self) -> Series: ...
    def var(self) -> Series: ...

class MultiIndex:
    def __init__(self, levels: dict[str, list[Any]]) -> None: ...
    @property
    def nlevels(self) -> int: ...
    @property
    def names(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def get_level_values(self, level: int) -> list[Any]: ...
    def get_tuple(self, pos: int) -> list[Any]: ...
    def swaplevel(self, a: int, b: int) -> MultiIndex: ...
    def droplevel(self, level: int) -> MultiIndex: ...
    def reorder_levels(self, order: list[int]) -> MultiIndex: ...

class Workbook:
    def __init__(self) -> None: ...
    def add_sheet(self, name: str, df: DataFrame) -> None: ...
    def get_sheet(self, name: str) -> DataFrame: ...
    @property
    def nsheets(self) -> int: ...
    @property
    def sheet_names(self) -> list[str]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> Workbook: ...

def read_csv_file(path: str, delimiter: str = ",", header: bool = True) -> DataFrame: ...
