// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-browser-cli-smoke-rs" reason="Existing code claimed during Score standardization until deterministic generator coverage lands.">
// SPEC-MANAGED: generated by `aw ec gen` from EC claim `live-wasm-capture-after-click` — fill the body.
// @ec live-wasm-capture-after-click
// @capability unmapped
#[test]
fn browser_cli_smoke() {
    // contract: bundle.schema_version == jet.browser.observation.v1
    // contract: bundle.layout_tree is non-empty
    // contract: bundle.paint_ops is non-empty
    // contract: bundle.hook_values includes the post-click counter value
    // contract: no python static server is used
    // fill: drive the in-process target and assert the contract above.
todo!("implement EC claim live-wasm-capture-after-click");
}

// </HANDWRITE>
