// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-renderer-layout-rs" reason="Existing code claimed during Score standardization until deterministic generator coverage lands.">
// SPEC-MANAGED: generated by `aw ec gen` from EC claim `full-jet-health-after-unit-repair` — fill the body.
// @ec full-jet-health-after-unit-repair
// @capability unmapped
#[test]
fn renderer_layout() {
    // contract: test gate no longer fails on projects/jet/wasm/tests/renderer_layout.rs stale v0 expectations
    // contract: renderer_layout remains a required test gate with zero ignored cases
    // fill: drive the in-process target and assert the contract above.
todo!("implement EC claim full-jet-health-after-unit-repair");
}

// </HANDWRITE>
