// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-wasm-dom-parity-gate-rs" reason="Existing code claimed during Score standardization until deterministic generator coverage lands.">
// SPEC-MANAGED: generated by `aw ec gen` from EC claim `full-jet-health-after-unit-repair` — fill the body.
// @ec full-jet-health-after-unit-repair
// @capability unmapped
use std::path::PathBuf;
use std::process::Command;

#[test]
fn wasm_dom_parity_gate() {
    // contract: test gate no longer fails on projects/jet/wasm/tests/renderer_layout.rs stale v0 expectations
    // contract: test gate remains required with skipped_count equal to 0
    // fill: drive the in-process target and assert the contract above.
    let output = run_renderer_layout_gate();
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "renderer_layout gate failed\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    assert!(
        stdout.contains("0 ignored"),
        "renderer_layout gate must remain required with zero ignored cases\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
}

fn run_renderer_layout_gate() -> std::process::Output {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    Command::new(cargo)
        .current_dir(workspace_root())
        .args([
            "test",
            "-p",
            "jet-wasm",
            "--test",
            "renderer_layout",
            "--",
            "--nocapture",
        ])
        .output()
        .expect("run jet-wasm renderer_layout gate")
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("jet package lives under projects/jet")
        .to_path_buf()
}

// </HANDWRITE>
