from typing import Optional

class ndarray:
    def __init__(self, data: list[float], shape: Optional[list[int]] = None) -> None: ...
    @staticmethod
    def zeros(shape: list[int]) -> ndarray: ...
    @staticmethod
    def ones(shape: list[int]) -> ndarray: ...
    @staticmethod
    def full(shape: list[int], value: float) -> ndarray: ...
    @staticmethod
    def arange(start: float, stop: float, step: float) -> ndarray: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    def tolist(self) -> list[float]: ...
    def sum(self) -> float: ...
    def mean(self) -> float: ...
    def min(self) -> Optional[float]: ...
    def max(self) -> Optional[float]: ...
    def std(self) -> float: ...
    def var(self) -> float: ...
    def median(self) -> Optional[float]: ...
    def reshape(self, shape: list[int]) -> ndarray: ...
    def flatten(self) -> ndarray: ...
    def transpose(self) -> ndarray: ...
    def dot(self, other: ndarray) -> ndarray: ...
    def sqrt(self) -> ndarray: ...
    def exp(self) -> ndarray: ...
    def log(self) -> ndarray: ...
    def abs(self) -> ndarray: ...
    def clip(self, min: float, max: float) -> ndarray: ...
    def cumsum(self) -> ndarray: ...
    def cumprod(self) -> ndarray: ...
    def argmin(self) -> Optional[int]: ...
    def argmax(self) -> Optional[int]: ...
    def sum_axis(self, axis: int) -> ndarray: ...
    def mean_axis(self, axis: int) -> ndarray: ...
    def __add__(self, other: ndarray) -> ndarray: ...
    def __sub__(self, other: ndarray) -> ndarray: ...
    def __mul__(self, other: ndarray) -> ndarray: ...
    def __truediv__(self, other: ndarray) -> ndarray: ...
    def __getitem__(self, index: list[int]) -> float: ...
    def __repr__(self) -> str: ...

class RandomState:
    def __init__(self, seed: int) -> None: ...
    def seed(self, seed: int) -> None: ...
    def rand(self, shape: list[int]) -> ndarray: ...
    def uniform(self, low: float, high: float, size: Optional[list[int]] = None) -> ndarray: ...
    def normal(self, loc: float, scale: float, size: Optional[list[int]] = None) -> ndarray: ...
    def randint(self, low: int, high: Optional[int] = None, size: Optional[list[int]] = None) -> ndarray: ...
    def binomial(self, n: int, p: float, size: Optional[list[int]] = None) -> ndarray: ...
    def poisson(self, lam: float, size: Optional[list[int]] = None) -> ndarray: ...
    def choice(self, n: int, size: Optional[int] = None, replace: bool = True) -> list[int]: ...

def array(data: list[float], shape: Optional[list[int]] = None) -> ndarray: ...
def zeros(shape: list[int]) -> ndarray: ...
def ones(shape: list[int]) -> ndarray: ...
def arange(start: float, stop: float, step: float) -> ndarray: ...
def linspace(start: float, stop: float, num: int) -> ndarray: ...
def full(shape: list[int], value: float) -> ndarray: ...
def eye(n: int) -> ndarray: ...
def diag(data: list[float]) -> ndarray: ...
