// SPEC-MANAGED: projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen_preamble.md#source
// CODEGEN-BEGIN
//! Sequence+ code generator
//!
//! Generates Python async call chain from a [`SequenceDef`]
//! (interaction/sequence section type):
//!
//! | Output file                    | Description                                  |
//! |--------------------------------|----------------------------------------------|
//! | `{sequence_id}_handlers.py`    | Async handler functions with `@sdd:implement` markers |
//!
//! The generator implements [`SpecIRGenerator`] and only accepts
//! [`SpecIR::SequencePlus`] variants.

use super::common::{
    GeneratedFile, GeneratorError, GeneratorSettings, Manifest, OverwritePolicy, SpecIRGenerator,
};
use crate::generate::diagrams::{ArrowType, MessageDef, SequenceDef};
use crate::generate::engine::TemplateEngine;
use crate::generate::spec_ir::SpecIR;

// ---------------------------------------------------------------------------
// SequencePlusGenerator
// ---------------------------------------------------------------------------
// CODEGEN-END
// SPEC-MANAGED: projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen.md#schema
// CODEGEN-BEGIN
/// SequencePlus generator (unit struct).
/// @spec projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen.md#schema
pub struct SequencePlusGenerator;
// CODEGEN-END

// SPEC-MANAGED: projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen_runtime.md#source
// CODEGEN-BEGIN

/// @spec projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen_runtime.md#source
impl SequencePlusGenerator {
    pub fn new() -> Self {
        Self
    }
}

/// @spec projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen_runtime.md#source
impl Default for SequencePlusGenerator {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// SpecIRGenerator impl
// ---------------------------------------------------------------------------

/// @spec projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen_runtime.md#source
impl SpecIRGenerator for SequencePlusGenerator {
    fn can_generate(&self, spec: &SpecIR) -> bool {
        matches!(spec, SpecIR::SequencePlus { .. })
    }

    fn template_dir(&self) -> &'static str {
        "sequence_plus"
    }

    fn generate_from_ir(
        &self,
        spec: &SpecIR,
        settings: &GeneratorSettings,
        engine: &TemplateEngine,
    ) -> Result<Manifest, GeneratorError> {
        let seq_def = match spec {
            SpecIR::SequencePlus { def, .. } => def,
            _ => {
                return Err(GeneratorError::SchemaError(
                    "SequencePlusGenerator: expected SpecIR::SequencePlus variant".into(),
                ))
            }
        };

        let mut manifest = Manifest::new();

        let file_name = format!("{}_handlers.py", seq_def.id.replace('-', "_"));
        let output_path = settings.output_dir.join(&file_name);

        if output_path.exists() {
            match settings.overwrite_policy {
                OverwritePolicy::Error => {
                    return Err(GeneratorError::OverwriteNotAllowed(output_path));
                }
                OverwritePolicy::Skip => {
                    manifest.add(GeneratedFile::skipped(output_path));
                    return Ok(manifest);
                }
                OverwritePolicy::Overwrite => {}
            }
        }

        let template_name = format!("{}/handlers.py.j2", self.template_dir());
        let content = if engine.has_template(&template_name) {
            engine.render(&template_name, &seq_def).map_err(|e| {
                GeneratorError::TemplateRenderError {
                    template: template_name.clone(),
                    message: e.to_string(),
                }
            })?
        } else {
            generate_sequence_python(seq_def)
        };

        manifest.add(GeneratedFile::written(output_path, &content));
        Ok(manifest)
    }
}

// ---------------------------------------------------------------------------
// Inline generator
// ---------------------------------------------------------------------------

fn to_snake(s: &str) -> String {
    use heck::ToSnakeCase;
    s.to_snake_case()
}

/// Group consecutive messages that originate from the same participant into
/// handler functions. Each "request" message (solid arrow) from a participant
/// to another participant becomes an async operation inside the handler.
fn generate_sequence_python(def: &SequenceDef) -> String {
    let mut output = String::from("# Generated by sdd\nfrom typing import Any\n\n");

    if def.messages.is_empty() {
        output.push_str("# No messages defined in sequence diagram\n");
        return output;
    }

    // Group messages into "conversations" initiated by the first sender.
    // Each group of outbound messages from one participant becomes an async handler.
    let handlers = group_into_handlers(&def.messages);

    for handler in &handlers {
        let fn_name = to_snake(&handler.name);
        let request_type = format!("{}Request", handler.name_pascal());
        let response_type = "Response".to_string();

        output.push_str(&format!(
            "async def handle_{}(request: {}) -> {}:\n",
            fn_name, request_type, response_type,
        ));

        for step in &handler.steps {
            match step {
                HandlerStep::AwaitCall { target, message } => {
                    let target_snake = to_snake(target);
                    let msg_snake = to_snake(message);
                    output.push_str(&format!(
                        "    # @sdd:implement {}\n    result = await {}.{}(request)\n",
                        msg_snake, target_snake, msg_snake,
                    ));
                }
                HandlerStep::Marker { label } => {
                    output.push_str(&format!("    # @sdd:implement {}\n", to_snake(label),));
                }
                HandlerStep::ReturnResponse { message } => {
                    output.push_str(&format!(
                        "    # @sdd:implement {}\n    return Response(status=200, body=result)\n",
                        to_snake(message),
                    ));
                }
            }
        }

        // If no return was generated, add a default
        if !handler
            .steps
            .iter()
            .any(|s| matches!(s, HandlerStep::ReturnResponse { .. }))
        {
            output.push_str("    return Response(status=200)\n");
        }

        output.push('\n');
    }

    output
}

// ---------------------------------------------------------------------------
// Handler grouping
// ---------------------------------------------------------------------------

struct Handler {
    name: String,
    steps: Vec<HandlerStep>,
}

/// @spec projects/agentic-workflow/tech-design/core/generate/generators/sequence_plus_gen_runtime.md#source
impl Handler {
    fn name_pascal(&self) -> String {
        use heck::ToPascalCase;
        self.name.to_pascal_case()
    }
}

enum HandlerStep {
    /// An async call to another participant
    AwaitCall { target: String, message: String },
    /// A processing marker
    #[allow(dead_code)]
    Marker { label: String },
    /// Return a response
    ReturnResponse { message: String },
}

/// Group messages into handler functions.
///
/// Strategy: Walk through messages. When we see a solid arrow (request)
/// from participant A to participant B, start or continue a handler for A.
/// When we see a dotted arrow (response) back, add a return step.
fn group_into_handlers(messages: &[MessageDef]) -> Vec<Handler> {
    let mut handlers: Vec<Handler> = Vec::new();
    let mut current_handler: Option<Handler> = None;
    let mut current_initiator: Option<String> = None;

    for msg in messages {
        let is_response = matches!(msg.arrow_type, ArrowType::Dotted | ArrowType::DottedOpen);

        if !is_response {
            // Outgoing request
            if current_initiator.as_deref() != Some(&msg.from) {
                // Start new handler group
                if let Some(h) = current_handler.take() {
                    handlers.push(h);
                }
                current_handler = Some(Handler {
                    name: msg.text.clone(),
                    steps: Vec::new(),
                });
                current_initiator = Some(msg.from.clone());
            }

            if let Some(ref mut h) = current_handler {
                h.steps.push(HandlerStep::AwaitCall {
                    target: msg.to.clone(),
                    message: msg.text.clone(),
                });
            }
        } else {
            // Response arrow
            if let Some(ref mut h) = current_handler {
                h.steps.push(HandlerStep::ReturnResponse {
                    message: msg.text.clone(),
                });
            }
        }
    }

    if let Some(h) = current_handler {
        handlers.push(h);
    }

    handlers
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generate::diagrams::{
        ArrowType, MessageDef, ParticipantDef, ParticipantType, SequenceDef,
    };
    use crate::generate::spec_ir::{SpecIR, SpecMetadata};
    use std::collections::HashMap;

    fn create_artifact_spec() -> SpecIR {
        let mut participants = HashMap::new();
        participants.insert(
            "client".to_string(),
            ParticipantDef {
                label: "Client".into(),
                participant_type: ParticipantType::Actor,
                description: None,
            },
        );
        participants.insert(
            "api".to_string(),
            ParticipantDef {
                label: "API Server".into(),
                participant_type: ParticipantType::Participant,
                description: None,
            },
        );
        participants.insert(
            "repository".to_string(),
            ParticipantDef {
                label: "Repository".into(),
                participant_type: ParticipantType::Participant,
                description: None,
            },
        );

        let messages = vec![
            MessageDef {
                from: "client".into(),
                to: "api".into(),
                text: "create_artifact".into(),
                arrow_type: ArrowType::Solid,
                activate: true,
                deactivate: false,
                description: None,
            },
            MessageDef {
                from: "api".into(),
                to: "repository".into(),
                text: "store_data".into(),
                arrow_type: ArrowType::Solid,
                activate: true,
                deactivate: false,
                description: None,
            },
            MessageDef {
                from: "repository".into(),
                to: "api".into(),
                text: "artifact_stored".into(),
                arrow_type: ArrowType::Dotted,
                activate: false,
                deactivate: true,
                description: None,
            },
            MessageDef {
                from: "api".into(),
                to: "client".into(),
                text: "201 Created".into(),
                arrow_type: ArrowType::Dotted,
                activate: false,
                deactivate: true,
                description: None,
            },
        ];

        SpecIR::SequencePlus {
            def: SequenceDef {
                id: "create-artifact".into(),
                title: Some("Create Artifact Flow".into()),
                participants,
                messages,
                loops: vec![],
                alts: vec![],
                notes: vec![],
                description: None,
            },
            metadata: SpecMetadata::default(),
        }
    }

    #[test]
    fn test_can_generate_sequence() {
        let gen = SequencePlusGenerator::new();
        assert!(gen.can_generate(&create_artifact_spec()));
    }

    #[test]
    fn test_cannot_generate_non_sequence() {
        use crate::generate::schema::JsonSchema;
        let gen = SequencePlusGenerator::new();
        let api_spec = SpecIR::Api {
            schema: JsonSchema::default(),
            metadata: SpecMetadata::default(),
        };
        assert!(!gen.can_generate(&api_spec));
    }

    #[test]
    fn test_generate_produces_one_file() {
        let spec = create_artifact_spec();
        let settings = GeneratorSettings {
            output_dir: std::path::PathBuf::from("/tmp/test_seq_gen"),
            ..Default::default()
        };
        let engine = crate::generate::engine::TemplateEngine::empty();
        let gen = SequencePlusGenerator::new();
        let manifest = gen.generate_from_ir(&spec, &settings, &engine).unwrap();

        assert_eq!(manifest.files.len(), 1);
        let name = manifest
            .files
            .keys()
            .next()
            .unwrap()
            .file_name()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        assert_eq!(name, "create_artifact_handlers.py");
    }

    #[test]
    fn test_generated_python_content() {
        let def = match &create_artifact_spec() {
            SpecIR::SequencePlus { def, .. } => def.clone(),
            _ => unreachable!(),
        };
        let content = generate_sequence_python(&def);

        // Should have async handler
        assert!(content.contains("async def handle_"));
        // Should have await calls
        assert!(content.contains("await"));
        // Should have @sdd:implement markers
        assert!(content.contains("# @sdd:implement"));
        // Should have Response return
        assert!(content.contains("return Response("));
    }

    #[test]
    fn test_empty_sequence() {
        let def = SequenceDef {
            id: "empty".into(),
            title: None,
            participants: HashMap::new(),
            messages: vec![],
            loops: vec![],
            alts: vec![],
            notes: vec![],
            description: None,
        };
        let content = generate_sequence_python(&def);
        assert!(content.contains("No messages defined"));
    }
}
// CODEGEN-END
