"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-large-explicit-source-fillback-and-lossless-exact-gen-source'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'large-explicit-source-fillback-and-lossless-exact-gen-source'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-large-explicit-source-fillback-and-lossless-exact-gen-source'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib explicit_ -- --nocapture', 'cargo test -p agentic-workflow --test cli_tests test_explicit_large_file_emits_single_dispatch_and_terminal_gen_source_json -- --nocapture')
REFERENCE_TOKENS = ('aw td create --from-source <file>', 'aw cb gen-source ... --dry-run')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib explicit_ -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests test_explicit_large_file_emits_single_dispatch_and_terminal_gen_source_json -- --nocapture`; repo-built `aw td create --from-source <file>` then emitted `aw cb gen-source ... --dry-run` on a 315,692-byte fixture'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:large-explicit-source-fillback-and-lossless-exact-gen-source: `cargo test -p agentic-workflow --lib explicit_ -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests test_explicit_large_file_emits_single_dispatch_and_terminal_gen_source_json -- --nocapture`; repo-built `aw td create --from-source <file>` then emitted `aw cb gen-source ... --dry-run` on a 315,692-byte fixture', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
