"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-agentic-workflow-ec-inventory-consistency'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'agentic-workflow-ec-inventory-consistency'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-agentic-workflow-ec-inventory-consistency'
TARGET_COMMANDS = ('python3 apps/agentic-workflow/external-contracts/src/inventory_parity.py',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = "`python3 apps/agentic-workflow/external-contracts/src/inventory_parity.py`; the canonical Python inventory preserves the 98 legacy case identities, applies only explicit compatibility corrections, and carries the required operational additions without using AW's own EC lifecycle as its oracle"
ASSERTIONS = ("Required outcome for project-local-td-and-ec-gates:agentic-workflow-ec-inventory-consistency: `python3 apps/agentic-workflow/external-contracts/src/inventory_parity.py`; the canonical Python inventory preserves the 98 legacy case identities, applies only explicit compatibility corrections, and carries the required operational additions without using AW's own EC lifecycle as its oracle", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
