"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-shared-artifact-producer-contract-source'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'shared-artifact-producer-contract-source'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-shared-artifact-producer-contract-source'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::artifact_producer::tests:: -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::artifact_producer::tests:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/artifact_producer.md; the source mirror implements the registered shared producer contract'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:shared-artifact-producer-contract-source: `cargo test -p agentic-workflow --lib cli::artifact_producer::tests:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/artifact_producer.md; the source mirror implements the registered shared producer contract', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
