"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-xml-handwrite-fill-protocol'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'xml-handwrite-fill-protocol'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-xml-handwrite-fill-protocol'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib pending_xml_handwrite -- --nocapture', 'cargo test -p agentic-workflow --lib xml_handwrite_marker_ -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib pending_xml_handwrite -- --nocapture`; `cargo test -p agentic-workflow --lib xml_handwrite_marker_ -- --nocapture`; pending XML scaffold markers enter a unique per-target fill queue and bind their tracker to the owning work item after payload application'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:xml-handwrite-fill-protocol: `cargo test -p agentic-workflow --lib pending_xml_handwrite -- --nocapture`; `cargo test -p agentic-workflow --lib xml_handwrite_marker_ -- --nocapture`; pending XML scaffold markers enter a unique per-target fill queue and bind their tracker to the owning work item after payload application', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
