"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-python-td-missing-source-fail-closed-routing'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'python-td-missing-source-fail-closed-routing'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-python-td-missing-source-fail-closed-routing'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test python_td_compiler -- --nocapture',)
REFERENCE_TOKENS = ('src/', 'pyproject.toml')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test python_td_compiler -- --nocapture`; configured Python projects route directory targets through the Python TD compiler even before `src/` or `pyproject.toml` exists, so a legacy Markdown directory cannot produce a false-green TD check'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:python-td-missing-source-fail-closed-routing: `cargo test -p agentic-workflow --test python_td_compiler -- --nocapture`; configured Python projects route directory targets through the Python TD compiler even before `src/` or `pyproject.toml` exists, so a legacy Markdown directory cannot produce a false-green TD check', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
