"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-current-session-guard-off-convergence'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'current-session-guard-off-convergence'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-current-session-guard-off-convergence'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib pretool_allows_current_session_callback_after_guard_off -- --nocapture',)
REFERENCE_TOKENS = ('aw guard off',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib pretool_allows_current_session_callback_after_guard_off -- --nocapture`; stale Codex/Claude hook callbacks consult live hook configuration, so `aw guard off` immediately permits the current session without dropping unrelated handlers'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:current-session-guard-off-convergence: `cargo test -p agentic-workflow --lib pretool_allows_current_session_callback_after_guard_off -- --nocapture`; stale Codex/Claude hook callbacks consult live hook configuration, so `aw guard off` immediately permits the current session without dropping unrelated handlers', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
