"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-init-sync-check-source'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'meta-doc-init-sync-check-source'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-init-sync-check-source'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::meta::tests:: -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::meta::tests:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/meta.md; the source mirror implements the registered producer claim'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:meta-doc-init-sync-check-source: `cargo test -p agentic-workflow --lib cli::meta::tests:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/meta.md; the source mirror implements the registered producer claim', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
