"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-prioritized-reviewed-graph-goal-selection'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'prioritized-reviewed-graph-goal-selection'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-prioritized-reviewed-graph-goal-selection'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ready_graph::tests -- --nocapture', 'cargo test -p agentic-workflow --test wi_reviewed_graph_goal_cli_test -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib ready_graph::tests -- --nocapture`; `cargo test -p agentic-workflow --test wi_reviewed_graph_goal_cli_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/reviewed-graph-goal-selection.md; the reviewed issue graph is the goal selector input, so epic direction, ready child order, terminal rollup, and invalid-graph remediation stay deterministic across epic and backlog roots'
ASSERTIONS = ('Required outcome for work-item-planning:prioritized-reviewed-graph-goal-selection: `cargo test -p agentic-workflow --lib ready_graph::tests -- --nocapture`; `cargo test -p agentic-workflow --test wi_reviewed_graph_goal_cli_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/reviewed-graph-goal-selection.md; the reviewed issue graph is the goal selector input, so epic direction, ready child order, terminal rollup, and invalid-graph remediation stay deterministic across epic and backlog roots', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
