"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-cli-verb-lifecycle-taxonomy-completeness'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'cli-verb-lifecycle-taxonomy-completeness'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-cli-verb-lifecycle-taxonomy-completeness'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib leaf_verb_paths_are_all_classified -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib leaf_verb_paths_are_all_classified -- --nocapture`; every live clap leaf, including read-only review and worktree-local guard bypass controls, carries an explicit lifecycle class and tracked-state mutation classification'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:cli-verb-lifecycle-taxonomy-completeness: `cargo test -p agentic-workflow --lib leaf_verb_paths_are_all_classified -- --nocapture`; every live clap leaf, including read-only review and worktree-local guard bypass controls, carries an explicit lifecycle class and tracked-state mutation classification', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
