"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-deterministic-staged-epic-change-planner'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'deterministic-staged-epic-change-planner'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-deterministic-staged-epic-change-planner'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test wi_two_stage_project_plan_cli_test -- --nocapture', 'cargo test -p agentic-workflow --test inventory_plan_review_cli_test -- --nocapture')
REFERENCE_TOKENS = ('aw wi plan',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test wi_two_stage_project_plan_cli_test -- --nocapture`; `cargo test -p agentic-workflow --test inventory_plan_review_cli_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/two-stage-project-plan.md; `aw wi plan` holds one stable root id while relaying normalize, reconcile, atomize, and strict zero-diff verify; compatibility planning verbs enter that same root, review and human decisions are separate evidence steps, and only plan-apply writes the tracker'
ASSERTIONS = ('Required outcome for work-item-planning:deterministic-staged-epic-change-planner: `cargo test -p agentic-workflow --test wi_two_stage_project_plan_cli_test -- --nocapture`; `cargo test -p agentic-workflow --test inventory_plan_review_cli_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/two-stage-project-plan.md; `aw wi plan` holds one stable root id while relaying normalize, reconcile, atomize, and strict zero-diff verify; compatibility planning verbs enter that same root, review and human decisions are separate evidence steps, and only plan-apply writes the tracker', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
