"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-scoped-td-fill-marker-completion'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'scoped-td-fill-marker-completion'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-scoped-td-fill-marker-completion'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cb_fill_apply_scopes_remaining_markers_to_active_changes -- --nocapture', 'cargo test -p agentic-workflow --test cli_tests test_apply_marker_replaces_block -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = "`cargo test -p agentic-workflow --lib cb_fill_apply_scopes_remaining_markers_to_active_changes -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests test_apply_marker_replaces_block -- --nocapture`; post-apply marker queues remain bounded to the active TD Changes paths, so foreign HANDWRITE gaps cannot block this work item's code-check"
ASSERTIONS = ("Required outcome for td-cb-lifecycle-automation:scoped-td-fill-marker-completion: `cargo test -p agentic-workflow --lib cb_fill_apply_scopes_remaining_markers_to_active_changes -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests test_apply_marker_replaces_block -- --nocapture`; post-apply marker queues remain bounded to the active TD Changes paths, so foreign HANDWRITE gaps cannot block this work item's code-check", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
