"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-three-host-agent-fleet-projection'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'three-host-agent-fleet-projection'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-three-host-agent-fleet-projection'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::init:: -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::init:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/init.md; one canonical templates/cli/mainthread/agents source projects the aw-* subagent fleet to claude, codex, and agy agent dirs via a shared model-tier table, with a read-only check and a narrow producer re-run flag'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:three-host-agent-fleet-projection: `cargo test -p agentic-workflow --lib cli::init:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/init.md; one canonical templates/cli/mainthread/agents source projects the aw-* subagent fleet to claude, codex, and agy agent dirs via a shared model-tier table, with a read-only check and a narrow producer re-run flag', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
