"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-stale-skill-retirement'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'stale-skill-retirement'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-stale-skill-retirement'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib install -- --nocapture', 'cargo test -p agentic-workflow --lib cli::init:: -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib install -- --nocapture`; `cargo test -p agentic-workflow --lib cli::init:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/init.md; gap: stale-skill-retirement; eight lifecycle-superseded and external-model-helper aw-* skills (aw-release-patch, aw-cb-claim, aw-cb-fill, aw-td-create, aw-capability, aw-codex-review, aw-gemini-explore-codebase, aw-gemini-explore-specs) are removed from templates and pruned from both live skill-tree installers on every install, with a fixture proving a retired name present on disk is pruned on next install (#1858)'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:stale-skill-retirement: `cargo test -p agentic-workflow --lib install -- --nocapture`; `cargo test -p agentic-workflow --lib cli::init:: -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/init.md; gap: stale-skill-retirement; eight lifecycle-superseded and external-model-helper aw-* skills (aw-release-patch, aw-cb-claim, aw-cb-fill, aw-td-create, aw-capability, aw-codex-review, aw-gemini-explore-codebase, aw-gemini-explore-specs) are removed from templates and pruned from both live skill-tree installers on every install, with a fixture proving a retired name present on disk is pruned on next install (#1858)', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
