"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-python-td-self-hosting-discovery'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'python-td-self-hosting-discovery'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-python-td-self-hosting-discovery'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test python_td_compiler python_td_compiler_discovers_self_hosting_bootstrap_with_stable_digest -- --nocapture',)
REFERENCE_TOKENS = ('./target/debug/aw td check apps/agentic-workflow/tech-design --project agentic-workflow --json', 'artifact:td-cb-lifecycle-automation/python-td-missing-source-fail-closed-routing')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test python_td_compiler python_td_compiler_discovers_self_hosting_bootstrap_with_stable_digest -- --nocapture`; `./target/debug/aw td check apps/agentic-workflow/tech-design --project agentic-workflow --json`; apps/agentic-workflow/tech-design/src/self_hosting.py; the stable `artifact:td-cb-lifecycle-automation/python-td-missing-source-fail-closed-routing` identity binds the bounded source module to this capability and gap/claim while existing Markdown TD artifacts remain compatibility/reference input'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:python-td-self-hosting-discovery: `cargo test -p agentic-workflow --test python_td_compiler python_td_compiler_discovers_self_hosting_bootstrap_with_stable_digest -- --nocapture`; `./target/debug/aw td check apps/agentic-workflow/tech-design --project agentic-workflow --json`; apps/agentic-workflow/tech-design/src/self_hosting.py; the stable `artifact:td-cb-lifecycle-automation/python-td-missing-source-fail-closed-routing` identity binds the bounded source module to this capability and gap/claim while existing Markdown TD artifacts remain compatibility/reference input', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
