"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-async-rust-handwrite-anchors'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'async-rust-handwrite-anchors'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-async-rust-handwrite-anchors'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib scaffold_async_function_anchors -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib scaffold_async_function_anchors -- --nocapture`; public, crate-visible, and private async Rust functions are valid bounded HANDWRITE anchors'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:async-rust-handwrite-anchors: `cargo test -p agentic-workflow --lib scaffold_async_function_anchors -- --nocapture`; public, crate-visible, and private async Rust functions are valid bounded HANDWRITE anchors', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
