"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-multi-agent-change-review-skill'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'multi-agent-change-review-skill'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-multi-agent-change-review-skill'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::init::tests::test_install_skills_projects_aw_change_review -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::init::tests::test_install_skills_projects_aw_change_review -- --nocapture`; apps/agentic-workflow/templates/cli/mainthread/skills/aw-change-review/SKILL.md; gap: multi-agent-change-review-skill; one producer-owned skill projects to Claude Code and Codex/AGY, reviews every cohesive author-owned change set before integration, rejects same-agent approval, and requires fix verification plus focused re-review'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:multi-agent-change-review-skill: `cargo test -p agentic-workflow --lib cli::init::tests::test_install_skills_projects_aw_change_review -- --nocapture`; apps/agentic-workflow/templates/cli/mainthread/skills/aw-change-review/SKILL.md; gap: multi-agent-change-review-skill; one producer-owned skill projects to Claude Code and Codex/AGY, reviews every cohesive author-owned change set before integration, rejects same-agent approval, and requires fix verification plus focused re-review', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
