"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-capability-control-plane-agent-facing-dx-baseline-trait'
CAPABILITY_ID = 'capability-control-plane'
USE_CASE_ID = 'agent-facing-dx-baseline-trait'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-capability-control-plane-agent-facing-dx-baseline-trait'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib agent_facing_trait_requires_developer_agent_experience_with_remediation -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib agent_facing_trait_requires_developer_agent_experience_with_remediation -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-dx-trait-derivation.md; the explicit agent_facing profile trait derives developer-agent-experience, names the CONTRIBUTING DX convention as its enforced contract, and reports the normal missing-baseline remediation'
ASSERTIONS = ('Required outcome for capability-control-plane:agent-facing-dx-baseline-trait: `cargo test -p agentic-workflow --lib agent_facing_trait_requires_developer_agent_experience_with_remediation -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-dx-trait-derivation.md; the explicit agent_facing profile trait derives developer-agent-experience, names the CONTRIBUTING DX convention as its enforced contract, and reports the normal missing-baseline remediation', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
