"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-aw-goal-verifiable-condition-loop'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'aw-goal-verifiable-condition-loop'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-aw-goal-verifiable-condition-loop'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::goal:: -- --nocapture', 'cargo test -p agentic-workflow --lib chain -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::goal:: -- --nocapture`; `cargo test -p agentic-workflow --lib chain -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-goal-condition-loop.md; gap: aw-goal-verifiable-condition-loop; a CLI-owned ad hoc verifiable condition loop records a prose intent plus one or more machine runnable gate commands as workspace scoped state and reports deterministically done, blocked, or gave up on budget or expiry, replacing the generic Stop-hook goal-loop skill for bounded work outside the WI lifecycle (#1897)'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:aw-goal-verifiable-condition-loop: `cargo test -p agentic-workflow --lib cli::goal:: -- --nocapture`; `cargo test -p agentic-workflow --lib chain -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-goal-condition-loop.md; gap: aw-goal-verifiable-condition-loop; a CLI-owned ad hoc verifiable condition loop records a prose intent plus one or more machine runnable gate commands as workspace scoped state and reports deterministically done, blocked, or gave up on budget or expiry, replacing the generic Stop-hook goal-loop skill for bounded work outside the WI lifecycle (#1897)', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
