"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-python-artifact-trace-code-check'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'python-artifact-trace-code-check'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-python-artifact-trace-code-check'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib python_artifact_code_check -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib python_artifact_code_check -- --nocapture`; apps/agentic-workflow/tech-design/logic/aw-python-artifact-trace-code-check.md; terminal closure must bind stable DDD identities, TD source/semantic lock, cold target digest, native unit result, EC review/lock, and required staged evidence'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:python-artifact-trace-code-check: `cargo test -p agentic-workflow --lib python_artifact_code_check -- --nocapture`; apps/agentic-workflow/tech-design/logic/aw-python-artifact-trace-code-check.md; terminal closure must bind stable DDD identities, TD source/semantic lock, cold target digest, native unit result, EC review/lock, and required staged evidence', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
