"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-ec-gen-post-implementation-phase-aware-handoff'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'ec-gen-post-implementation-phase-aware-handoff'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-ec-gen-post-implementation-phase-aware-handoff'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ec_gen_next_action_ -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib ec_gen_next_action_ -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; fresh EC-first generation still hands off to TD authoring, while post-review regeneration for cb_filled WIs runs the newly current EC verifier instead of emitting an invalid td create rewind'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:ec-gen-post-implementation-phase-aware-handoff: `cargo test -p agentic-workflow --lib ec_gen_next_action_ -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; fresh EC-first generation still hands off to TD authoring, while post-review regeneration for cb_filled WIs runs the newly current EC verifier instead of emitting an invalid td create rewind', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
