"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-capability-control-plane-ddd-context-map-contract'
CAPABILITY_ID = 'capability-control-plane'
USE_CASE_ID = 'ddd-context-map-contract'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-capability-control-plane-ddd-context-map-contract'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test ddd_context_map_test -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test ddd_context_map_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/ddd-context-map-contract.md; stable DDD identities, context boundaries, relation vocabulary, and projection ownership validate before narrative or source artifacts use them'
ASSERTIONS = ('Required outcome for capability-control-plane:ddd-context-map-contract: `cargo test -p agentic-workflow --test ddd_context_map_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/ddd-context-map-contract.md; stable DDD identities, context boundaries, relation vocabulary, and projection ownership validate before narrative or source artifacts use them', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
