"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-python-ec-staged-verification'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'python-ec-staged-verification'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-python-ec-staged-verification'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test ec_python_review_lock -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test ec_python_review_lock -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-staged-verification.md; Python EC cases declare promise, oracle, target, thresholds where applicable, and external evidence; core verifies behavior/security while operational verifies stability/efficiency and fails missing evidence'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:python-ec-staged-verification: `cargo test -p agentic-workflow --test ec_python_review_lock -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-staged-verification.md; Python EC cases declare promise, oracle, target, thresholds where applicable, and external evidence; core verifies behavior/security while operational verifies stability/efficiency and fails missing evidence', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
