"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-python-ec-missing-scaffold-recovery'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'python-ec-missing-scaffold-recovery'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-python-ec-missing-scaffold-recovery'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test ec_python_inventory_check -- --nocapture',)
REFERENCE_TOKENS = ('./target/debug/aw ec --help',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test ec_python_inventory_check -- --nocapture`; `./target/debug/aw ec --help`; apps/agentic-workflow/tech-design/core/logic/python-ec-inventory-check.md; a missing external-contracts/pyproject.toml emits an aw.cli.v1 continuation with one runnable Python scaffold command, draft creates only pyproject/src/evidence artifacts with an exact follow-up check, and help no longer teaches Markdown as the canonical authoring path'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:python-ec-missing-scaffold-recovery: `cargo test -p agentic-workflow --test ec_python_inventory_check -- --nocapture`; `./target/debug/aw ec --help`; apps/agentic-workflow/tech-design/core/logic/python-ec-inventory-check.md; a missing external-contracts/pyproject.toml emits an aw.cli.v1 continuation with one runnable Python scaffold command, draft creates only pyproject/src/evidence artifacts with an exact follow-up check, and help no longer teaches Markdown as the canonical authoring path', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
