"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-agent-backed-inventory-plan-review'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'agent-backed-inventory-plan-review'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-agent-backed-inventory-plan-review'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test inventory_plan_review_cli_test -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test inventory_plan_review_cli_test -- --nocapture`; epicize, atomize, and prioritize default to digest-bound independent agent review, reject same-agent evidence, preserve explicit human-only policy, and authorize only a chain-valid next command from accepted evidence'
ASSERTIONS = ('Required outcome for work-item-planning:agent-backed-inventory-plan-review: `cargo test -p agentic-workflow --test inventory_plan_review_cli_test -- --nocapture`; epicize, atomize, and prioritize default to digest-bound independent agent review, reject same-agent evidence, preserve explicit human-only policy, and authorize only a chain-valid next command from accepted evidence', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
