"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-numeric-td-skeleton-ids'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'numeric-td-skeleton-ids'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-numeric-td-skeleton-ids'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib initialize_td_spec_skeleton -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib initialize_td_spec_skeleton -- --nocapture`; apps/agentic-workflow/tech-design/logic/numeric-td-skeleton-id.md'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:numeric-td-skeleton-ids: `cargo test -p agentic-workflow --lib initialize_td_spec_skeleton -- --nocapture`; apps/agentic-workflow/tech-design/logic/numeric-td-skeleton-id.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
