"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-persistent-guard-policy-and-agy-adapter'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'persistent-guard-policy-and-agy-adapter'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-persistent-guard-policy-and-agy-adapter'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib guard -- --nocapture',)
REFERENCE_TOKENS = ('aw guard on/off', 'aw guard bypass')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib guard -- --nocapture`; `aw guard on/off` commit only their changed repo-tracked Codex/Claude policy files, while AGY adds a preserving user-global adapter and temporary exceptions use expiring worktree-local `aw guard bypass` state'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:persistent-guard-policy-and-agy-adapter: `cargo test -p agentic-workflow --lib guard -- --nocapture`; `aw guard on/off` commit only their changed repo-tracked Codex/Claude policy files, while AGY adds a preserving user-global adapter and temporary exceptions use expiring worktree-local `aw guard bypass` state', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
