"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-reviewed-legacy-to-python-ec-lock-replacement'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'reviewed-legacy-to-python-ec-lock-replacement'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-reviewed-legacy-to-python-ec-lock-replacement'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib reviewed_python_wi_replaces_legacy_inventory_lock_without_weakening_global_guard -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib reviewed_python_wi_replaces_legacy_inventory_lock_without_weakening_global_guard -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-review-lock.md; a root-owned Python WI may replace a legacy aw.toml/Markdown EC lock only after digest-current independent review of the canonical pyproject bundle, while project-global locking and every other removed-contract transition remain fail closed'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:reviewed-legacy-to-python-ec-lock-replacement: `cargo test -p agentic-workflow --lib reviewed_python_wi_replaces_legacy_inventory_lock_without_weakening_global_guard -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-review-lock.md; a root-owned Python WI may replace a legacy aw.toml/Markdown EC lock only after digest-current independent review of the canonical pyproject bundle, while project-global locking and every other removed-contract transition remain fail closed', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
