"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-capability-control-plane-python-artifact-readiness'
CAPABILITY_ID = 'capability-control-plane'
USE_CASE_ID = 'python-artifact-readiness'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-capability-control-plane-python-artifact-readiness'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test python_artifact_readiness -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test python_artifact_readiness -- --nocapture`; apps/agentic-workflow/tech-design/logic/aw-python-artifact-readiness.md; capability and health share one read-only Python TD/EC readiness projection with executable remediation for missing inventory or evidence'
ASSERTIONS = ('Required outcome for capability-control-plane:python-artifact-readiness: `cargo test -p agentic-workflow --test python_artifact_readiness -- --nocapture`; apps/agentic-workflow/tech-design/logic/aw-python-artifact-readiness.md; capability and health share one read-only Python TD/EC readiness projection with executable remediation for missing inventory or evidence', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
