"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-ownership-matrix-source'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'meta-doc-ownership-matrix-source'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-ownership-matrix-source'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib meta_doc_ownership -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib meta_doc_ownership -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/meta_docs.md; the source mirror implements the same ownership-matrix claim without inventing an unregistered claim id'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:meta-doc-ownership-matrix-source: `cargo test -p agentic-workflow --lib meta_doc_ownership -- --nocapture`; apps/agentic-workflow/tech-design/surface/interfaces/src/meta_docs.md; the source mirror implements the same ownership-matrix claim without inventing an unregistered claim id', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
