"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-python-td-native-target-collision-safety'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'python-td-native-target-collision-safety'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-python-td-native-target-collision-safety'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test python_td_target -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test python_td_target -- --nocapture`; Rust, Python, and TypeScript native emitters preflight the complete candidate write set, reject unowned existing-file collisions before mutation, preserve unrelated project files while atomically updating explicitly generator-owned paths, and declare manifest/source/test paths in the goal prompt writable scope'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:python-td-native-target-collision-safety: `cargo test -p agentic-workflow --test python_td_target -- --nocapture`; Rust, Python, and TypeScript native emitters preflight the complete candidate write set, reject unowned existing-file collisions before mutation, preserve unrelated project files while atomically updating explicitly generator-owned paths, and declare manifest/source/test paths in the goal prompt writable scope', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
