"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-python-ec-inventory-check'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'python-ec-inventory-check'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-python-ec-inventory-check'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test ec_python_inventory_check -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = "`cargo test -p agentic-workflow --test ec_python_inventory_check -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-inventory-check.md; every project reads a hand-authored external-contracts Python project's pyproject inventory without importing or executing EC source and requires stable capability/use-case/dimension records with TD or post-generation applicability"
ASSERTIONS = ("Required outcome for project-local-td-and-ec-gates:python-ec-inventory-check: `cargo test -p agentic-workflow --test ec_python_inventory_check -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-inventory-check.md; every project reads a hand-authored external-contracts Python project's pyproject inventory without importing or executing EC source and requires stable capability/use-case/dimension records with TD or post-generation applicability", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
