"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-repo-view-command-and-desktop-product-removal'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'repo-view-command-and-desktop-product-removal'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-repo-view-command-and-desktop-product-removal'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test cli_tests legacy_cli_removal_test -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test cli_tests legacy_cli_removal_test -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-view-removal.md'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:repo-view-command-and-desktop-product-removal: `cargo test -p agentic-workflow --test cli_tests legacy_cli_removal_test -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-view-removal.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
