"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-root-owned-ec-production-required-verdict'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'root-owned-ec-production-required-verdict'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-root-owned-ec-production-required-verdict'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib wi_change_lifecycle_step_routes_by_phase -- --nocapture', 'cargo test -p agentic-workflow --lib lifecycle_action_for_post_fill_phases_records_ec_verdict -- --nocapture', 'cargo test -p agentic-workflow --lib ec_verify_required_only_skips_advisory_cases -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = "`cargo test -p agentic-workflow --lib wi_change_lifecycle_step_routes_by_phase -- --nocapture`; `cargo test -p agentic-workflow --lib lifecycle_action_for_post_fill_phases_records_ec_verdict -- --nocapture`; `cargo test -p agentic-workflow --lib ec_verify_required_only_skips_advisory_cases -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; WI/capability loop verdicts use terminal code-check's production-required case filter, while manual unscoped EC verification retains the all-cases diagnostic mode"
ASSERTIONS = ("Required outcome for project-local-td-and-ec-gates:root-owned-ec-production-required-verdict: `cargo test -p agentic-workflow --lib wi_change_lifecycle_step_routes_by_phase -- --nocapture`; `cargo test -p agentic-workflow --lib lifecycle_action_for_post_fill_phases_records_ec_verdict -- --nocapture`; `cargo test -p agentic-workflow --lib ec_verify_required_only_skips_advisory_cases -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; WI/capability loop verdicts use terminal code-check's production-required case filter, while manual unscoped EC verification retains the all-cases diagnostic mode", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
