"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-ec-needs-revision-existing-source-routing'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'ec-needs-revision-existing-source-routing'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-ec-needs-revision-existing-source-routing'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ec_needs_revision_ -- --nocapture', 'cargo test -p agentic-workflow --lib ec_review_agent_needs_revision_routes_to_bounded_fill -- --nocapture')
REFERENCE_TOKENS = ('aw ec fill',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib ec_needs_revision_ -- --nocapture`; `cargo test -p agentic-workflow --lib ec_review_agent_needs_revision_routes_to_bounded_fill -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; review evidence may route only to an existing external-contract Markdown source or an existing legacy TD-derived source, so emitted `aw ec fill` commands are executable'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:ec-needs-revision-existing-source-routing: `cargo test -p agentic-workflow --lib ec_needs_revision_ -- --nocapture`; `cargo test -p agentic-workflow --lib ec_review_agent_needs_revision_routes_to_bounded_fill -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; review evidence may route only to an existing external-contract Markdown source or an existing legacy TD-derived source, so emitted `aw ec fill` commands are executable', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
