"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-capability-control-plane-ddd-meta-projection-contract'
CAPABILITY_ID = 'capability-control-plane'
USE_CASE_ID = 'ddd-meta-projection-contract'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-capability-control-plane-ddd-meta-projection-contract'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test ddd_meta_projection_test -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test ddd_meta_projection_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/ddd-meta-projection-contract.md; capability, README, contributing, EC, TD, and source surfaces have unique DDD narrative fact ownership independent of disposable render output'
ASSERTIONS = ('Required outcome for capability-control-plane:ddd-meta-projection-contract: `cargo test -p agentic-workflow --test ddd_meta_projection_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/ddd-meta-projection-contract.md; capability, README, contributing, EC, TD, and source surfaces have unique DDD narrative fact ownership independent of disposable render output', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
