"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-marker-free-post-fill-evidence'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'marker-free-post-fill-evidence'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-marker-free-post-fill-evidence'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test cli_tests cb_fill_test::test_marker_free_brief_commits_declared_evidence_and_preserves_unrelated_dirty_path -- --nocapture',)
REFERENCE_TOKENS = ('cb_filled', 'aw cb fill')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test cli_tests cb_fill_test::test_marker_free_brief_commits_declared_evidence_and_preserves_unrelated_dirty_path -- --nocapture`; after the last marker, including re-entry from `cb_filled`, `aw cb fill` commits declared Changes evidence while preserving unrelated dirty work untouched'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:marker-free-post-fill-evidence: `cargo test -p agentic-workflow --test cli_tests cb_fill_test::test_marker_free_brief_commits_declared_evidence_and_preserves_unrelated_dirty_path -- --nocapture`; after the last marker, including re-entry from `cb_filled`, `aw cb fill` commits declared Changes evidence while preserving unrelated dirty work untouched', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
