"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-init-sync-check'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'meta-doc-init-sync-check'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-init-sync-check'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::meta::tests:: -- --nocapture', 'cargo test -p agentic-workflow --lib leaf_verb_paths_are_all_classified -- --nocapture')
REFERENCE_TOKENS = ('aw new',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::meta::tests:: -- --nocapture`; `cargo test -p agentic-workflow --lib leaf_verb_paths_are_all_classified -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-meta-doc-producer.md; one producer registry owns skeleton creation, marker-only synchronization, read-only drift diagnostics, chainable output, and legacy `aw new` delegation'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:meta-doc-init-sync-check: `cargo test -p agentic-workflow --lib cli::meta::tests:: -- --nocapture`; `cargo test -p agentic-workflow --lib leaf_verb_paths_are_all_classified -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-meta-doc-producer.md; one producer registry owns skeleton creation, marker-only synchronization, read-only drift diagnostics, chainable output, and legacy `aw new` delegation', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
