"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-workflow-root-runner-closed-workflow-lock-release'
CAPABILITY_ID = 'workflow-root-runner'
USE_CASE_ID = 'closed-workflow-lock-release'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-workflow-root-runner-closed-workflow-lock-release'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib issue_lock_view_ignores_closed_issue_with_stale_lock_projection -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib issue_lock_view_ignores_closed_issue_with_stale_lock_projection -- --nocapture`; lock discovery reads the configured tracker so closed/rejected items cannot retain a stale local projection that blocks unrelated TD/CB work'
ASSERTIONS = ('Required outcome for workflow-root-runner:closed-workflow-lock-release: `cargo test -p agentic-workflow --lib issue_lock_view_ignores_closed_issue_with_stale_lock_projection -- --nocapture`; lock discovery reads the configured tracker so closed/rejected items cannot retain a stale local projection that blocks unrelated TD/CB work', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
