"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-author-time-handwrite-anchor-contract'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'author-time-handwrite-anchor-contract'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-author-time-handwrite-anchor-contract'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib td_authoring_ -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib td_authoring_ -- --nocapture`; Changes payload guidance and apply-time validation reject markerless existing hand-written Rust modifications before TD generation, while existing non-Rust artifacts stay diff-evidenced without a Rust marker'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:author-time-handwrite-anchor-contract: `cargo test -p agentic-workflow --lib td_authoring_ -- --nocapture`; Changes payload guidance and apply-time validation reject markerless existing hand-written Rust modifications before TD generation, while existing non-Rust artifacts stay diff-evidenced without a Rust marker', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
