"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-workflow-root-runner-python-artifact-protocol'
CAPABILITY_ID = 'workflow-root-runner'
USE_CASE_ID = 'python-artifact-protocol'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-workflow-root-runner-python-artifact-protocol'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test python_artifact_protocol_test -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test python_artifact_protocol_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-artifact-project-protocol.md; CPython Python-v1 artifacts declare safe source, dependency, entrypoint, and evidence boundaries in pyproject.toml before later TD or EC adapters consume them'
ASSERTIONS = ('Required outcome for workflow-root-runner:python-artifact-protocol: `cargo test -p agentic-workflow --test python_artifact_protocol_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-artifact-project-protocol.md; CPython Python-v1 artifacts declare safe source, dependency, entrypoint, and evidence boundaries in pyproject.toml before later TD or EC adapters consume them', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
