"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-cross-checkout-chat-command-and-shared-channel-removal'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'cross-checkout-chat-command-and-shared-channel-removal'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-cross-checkout-chat-command-and-shared-channel-removal'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test cli_tests legacy_cli_removal_test -- --nocapture', 'cargo test -p agentic-workflow --lib test_install_skills_prunes_aw_chat_listen -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test cli_tests legacy_cli_removal_test -- --nocapture`; `cargo test -p agentic-workflow --lib test_install_skills_prunes_aw_chat_listen -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-chat-removal.md'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:cross-checkout-chat-command-and-shared-channel-removal: `cargo test -p agentic-workflow --test cli_tests legacy_cli_removal_test -- --nocapture`; `cargo test -p agentic-workflow --lib test_install_skills_prunes_aw_chat_listen -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-chat-removal.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
