"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-existing-project-standardization-project-profile-conformance-review'
CAPABILITY_ID = 'existing-project-standardization'
USE_CASE_ID = 'project-profile-conformance-review'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-existing-project-standardization-project-profile-conformance-review'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::review',)
REFERENCE_TOKENS = ('./target/debug/aw review --project agentic-workflow',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::review`; `./target/debug/aw review --project agentic-workflow`; apps/agentic-workflow/tech-design/config/aw-review-resolve-project-profile-cli-report-skeleton.md'
ASSERTIONS = ('Required outcome for existing-project-standardization:project-profile-conformance-review: `cargo test -p agentic-workflow --lib cli::review`; `./target/debug/aw review --project agentic-workflow`; apps/agentic-workflow/tech-design/config/aw-review-resolve-project-profile-cli-report-skeleton.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
