"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-epic-child-graph-terminal-rollup'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'epic-child-graph-terminal-rollup'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-epic-child-graph-terminal-rollup'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib open_epic_with_ -- --nocapture', 'cargo test -p agentic-workflow --lib epic_parent_relation_ -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib open_epic_with_ -- --nocapture`; `cargo test -p agentic-workflow --lib epic_parent_relation_ -- --nocapture`; open epics discover tracker-backed parent relations across open and closed WIs, dispatch unfinished children, close after every child is terminal, and re-atomize only when no child graph exists'
ASSERTIONS = ('Required outcome for work-item-planning:epic-child-graph-terminal-rollup: `cargo test -p agentic-workflow --lib open_epic_with_ -- --nocapture`; `cargo test -p agentic-workflow --lib epic_parent_relation_ -- --nocapture`; open epics discover tracker-backed parent relations across open and closed WIs, dispatch unfinished children, close after every child is terminal, and re-atomize only when no child graph exists', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
