"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-workflow-root-runner-python-artifact-model-compatibility-parser'
CAPABILITY_ID = 'workflow-root-runner'
USE_CASE_ID = 'python-artifact-model-compatibility-parser'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-workflow-root-runner-python-artifact-model-compatibility-parser'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test artifact_model_config_test -- --nocapture',)
REFERENCE_TOKENS = ('legacy', 'python-v1')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test artifact_model_config_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-artifact-model-selector.md; historical `legacy` / `python-v1` configuration remains readable without giving a local overlay or stale value authority to disable the canonical Python lifecycle'
ASSERTIONS = ('Required outcome for workflow-root-runner:python-artifact-model-compatibility-parser: `cargo test -p agentic-workflow --test artifact_model_config_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-artifact-model-selector.md; historical `legacy` / `python-v1` configuration remains readable without giving a local overlay or stale value authority to disable the canonical Python lifecycle', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
