"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-project-scoped-planner-dev-research-agent-fleet'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'project-scoped-planner-dev-research-agent-fleet'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-project-scoped-planner-dev-research-agent-fleet'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::init::tests::test_project_role_fleet_uses_registry_scope_and_model_matrix',)
REFERENCE_TOKENS = ('apps/*', 'projects/mamba')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::init::tests::test_project_role_fleet_uses_registry_scope_and_model_matrix`; apps/agentic-workflow/tech-design/surface/interfaces/src/init.md; direct `apps/*` registry projects plus `projects/mamba` receive independently scoped planner, dev, and read-only research roles on Claude, Codex, and AGY, with the three approved model/reasoning profiles and independent EC review preserved'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:project-scoped-planner-dev-research-agent-fleet: `cargo test -p agentic-workflow --lib cli::init::tests::test_project_role_fleet_uses_registry_scope_and_model_matrix`; apps/agentic-workflow/tech-design/surface/interfaces/src/init.md; direct `apps/*` registry projects plus `projects/mamba` receive independently scoped planner, dev, and read-only research roles on Claude, Codex, and AGY, with the three approved model/reasoning profiles and independent EC review preserved', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
