"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-shell-text-source-unit-cold-replay'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'shell-text-source-unit-cold-replay'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-shell-text-source-unit-cold-replay'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib canonical_shell_text_source_unit_accepts_shebang_and_hash_markers',)
REFERENCE_TOKENS = ('.sh', '.bash', '.zsh')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib canonical_shell_text_source_unit_accepts_shebang_and_hash_markers`; canonical `.sh`, `.bash`, and `.zsh` whole-file text source units retain a leading shebang and exact hash-comment ownership markers without requiring shell AST parsing'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:shell-text-source-unit-cold-replay: `cargo test -p agentic-workflow --lib canonical_shell_text_source_unit_accepts_shebang_and_hash_markers`; canonical `.sh`, `.bash`, and `.zsh` whole-file text source units retain a leading shebang and exact hash-comment ownership markers without requiring shell AST parsing', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
