"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-python-ec-review-lock'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'python-ec-review-lock'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-python-ec-review-lock'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test ec_python_review_lock -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test ec_python_review_lock -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-review-lock.md; an explicit Python-v1 project binds independent agent/human/deferred EC approval and the EC lock to every normalized Python source plus declared dependency and pyproject inventory input, rejects same-author agent review, and invalidates stale evidence deterministically'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:python-ec-review-lock: `cargo test -p agentic-workflow --test ec_python_review_lock -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-ec-review-lock.md; an explicit Python-v1 project binds independent agent/human/deferred EC approval and the EC lock to every normalized Python source plus declared dependency and pyproject inventory input, rejects same-author agent review, and invalidates stale evidence deterministically', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
