"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-existing-project-standardization-aw-review-skill-and-doc-projection'
CAPABILITY_ID = 'existing-project-standardization'
USE_CASE_ID = 'aw-review-skill-and-doc-projection'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-existing-project-standardization-aw-review-skill-and-doc-projection'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::review', 'cargo test -p agentic-workflow --lib cli::review_doc_projection', 'cargo test -p agentic-workflow --lib cli::init::tests::install_claude_skills_writes_aw_review_skill')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::review`; `cargo test -p agentic-workflow --lib cli::review_doc_projection`; `cargo test -p agentic-workflow --lib cli::init::tests::install_claude_skills_writes_aw_review_skill`; apps/agentic-workflow/tech-design/validate/review-skill-doc-trait-projection-with-drift-tests.md'
ASSERTIONS = ('Required outcome for existing-project-standardization:aw-review-skill-and-doc-projection: `cargo test -p agentic-workflow --lib cli::review`; `cargo test -p agentic-workflow --lib cli::review_doc_projection`; `cargo test -p agentic-workflow --lib cli::init::tests::install_claude_skills_writes_aw_review_skill`; apps/agentic-workflow/tech-design/validate/review-skill-doc-trait-projection-with-drift-tests.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
