"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-canonical-app-lib-td-fill-scope-reconciliation'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'canonical-app-lib-td-fill-scope-reconciliation'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-canonical-app-lib-td-fill-scope-reconciliation'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib canonical_td_changes_path_queues_app_marker', 'cargo test -p agentic-workflow --lib whole_worktree_walk_includes_apps_and_libs')
REFERENCE_TOKENS = ('apps/<name>', 'libs/<name>')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib canonical_td_changes_path_queues_app_marker`; `cargo test -p agentic-workflow --lib whole_worktree_walk_includes_apps_and_libs`; canonical `apps/<name>` and `libs/<name>` Changes paths queue their HANDWRITE markers and zero-marker re-entry records the normal filled lifecycle phase'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:canonical-app-lib-td-fill-scope-reconciliation: `cargo test -p agentic-workflow --lib canonical_td_changes_path_queues_app_marker`; `cargo test -p agentic-workflow --lib whole_worktree_walk_includes_apps_and_libs`; canonical `apps/<name>` and `libs/<name>` Changes paths queue their HANDWRITE markers and zero-marker re-entry records the normal filled lifecycle phase', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
