"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-new-project-epic-configuration-bootstrap'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'new-project-epic-configuration-bootstrap'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-new-project-epic-configuration-bootstrap'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib epic_project_label_dispatch_bootstraps_valid_unregistered_project -- --nocapture', 'cargo test -p agentic-workflow --lib conf_init_ -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib epic_project_label_dispatch_bootstraps_valid_unregistered_project -- --nocapture`; `cargo test -p agentic-workflow --lib conf_init_ -- --nocapture`; apps/agentic-workflow/tech-design/semantic/aw-epic-project-label-dispatch.md; a valid unregistered tracker identity routes through idempotent project-local configuration and META-doc producers before atomization'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:new-project-epic-configuration-bootstrap: `cargo test -p agentic-workflow --lib epic_project_label_dispatch_bootstraps_valid_unregistered_project -- --nocapture`; `cargo test -p agentic-workflow --lib conf_init_ -- --nocapture`; apps/agentic-workflow/tech-design/semantic/aw-epic-project-label-dispatch.md; a valid unregistered tracker identity routes through idempotent project-local configuration and META-doc producers before atomization', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
