"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-ec-lock-removal-migration-guard'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'ec-lock-removal-migration-guard'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-ec-lock-removal-migration-guard'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ec_lock_refuses_to_overwrite_when_current_ir_drops_locked_contracts', 'cargo test -p agentic-workflow --lib health_marks_ec_lock_removals_as_a_migration_hitl_blocker')
REFERENCE_TOKENS = ('aw ec lock',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib ec_lock_refuses_to_overwrite_when_current_ir_drops_locked_contracts`; `cargo test -p agentic-workflow --lib health_marks_ec_lock_removals_as_a_migration_hitl_blocker`; removed locked EC entries become a migration-required HITL blocker and cannot be silently dropped by `aw ec lock`'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:ec-lock-removal-migration-guard: `cargo test -p agentic-workflow --lib ec_lock_refuses_to_overwrite_when_current_ir_drops_locked_contracts`; `cargo test -p agentic-workflow --lib health_marks_ec_lock_removals_as_a_migration_hitl_blocker`; removed locked EC entries become a migration-required HITL blocker and cannot be silently dropped by `aw ec lock`', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
