"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-python-self-health-policy-reconciliation'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'python-self-health-policy-reconciliation'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-python-self-health-policy-reconciliation'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib python_readiness_ -- --nocapture', 'cargo test -p agentic-workflow --lib claim_closure_without_td_evidence_policy_does_not_scan_td_inventory -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = "`cargo test -p agentic-workflow --lib python_readiness_ -- --nocapture`; `cargo test -p agentic-workflow --lib claim_closure_without_td_evidence_policy_does_not_scan_td_inventory -- --nocapture`; Python artifact readiness preserves self-AW's advisory EC state unless a configured/evaluated gate fails, while claim closure does not scan legacy Markdown TD capability references when the active self-hosting policy does not require TD artifact evidence"
ASSERTIONS = ("Required outcome for td-cb-lifecycle-automation:python-self-health-policy-reconciliation: `cargo test -p agentic-workflow --lib python_readiness_ -- --nocapture`; `cargo test -p agentic-workflow --lib claim_closure_without_td_evidence_policy_does_not_scan_td_inventory -- --nocapture`; Python artifact readiness preserves self-AW's advisory EC state unless a configured/evaluated gate fails, while claim closure does not scan legacy Markdown TD capability references when the active self-hosting policy does not require TD artifact evidence", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
