"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-remote-cb-fill-hydration'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'remote-cb-fill-hydration'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-remote-cb-fill-hydration'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib wi_change_lifecycle_step_routes_by_phase -- --nocapture', 'cargo test -p agentic-workflow --test cli_tests cb_fill_brief_hydrates_missing_remote_projection -- --nocapture')
REFERENCE_TOKENS = ('aw cb fill <id>', '/tmp/aw')
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib wi_change_lifecycle_step_routes_by_phase -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests cb_fill_brief_hydrates_missing_remote_projection -- --nocapture`; the authoritative goal phase projection emits canonical `aw cb fill <id>`, and that exact public surface hydrates a missing `/tmp/aw` projection from the configured tracker before creating the marker-fill lock'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:remote-cb-fill-hydration: `cargo test -p agentic-workflow --lib wi_change_lifecycle_step_routes_by_phase -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests cb_fill_brief_hydrates_missing_remote_projection -- --nocapture`; the authoritative goal phase projection emits canonical `aw cb fill <id>`, and that exact public surface hydrates a missing `/tmp/aw` projection from the configured tracker before creating the marker-fill lock', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
