"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-project-qualified-terminal-td-resolution'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'project-qualified-terminal-td-resolution'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-project-qualified-terminal-td-resolution'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test cli_tests test_code_check_prefers_project_td_when_implements_cache_is_absent -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test cli_tests test_code_check_prefers_project_td_when_implements_cache_is_absent -- --nocapture`; issue-owned TD resolution preserves exact workflow scope and falls back only to the configured project-qualified TD root'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:project-qualified-terminal-td-resolution: `cargo test -p agentic-workflow --test cli_tests test_code_check_prefers_project_td_when_implements_cache_is_absent -- --nocapture`; issue-owned TD resolution preserves exact workflow scope and falls back only to the configured project-qualified TD root', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
