"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-existing-project-standardization-service-workload-profile-derivation'
CAPABILITY_ID = 'existing-project-standardization'
USE_CASE_ID = 'service-workload-profile-derivation'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-existing-project-standardization-service-workload-profile-derivation'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib stateful_storage_selects_the_statefulset_service_profile', 'cargo test -p agentic-workflow --lib known_traits_include_every_doc_mirror_trait_def', 'cargo test -p agentic-workflow --test cli_tests root_trait_coverage')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib stateful_storage_selects_the_statefulset_service_profile`; `cargo test -p agentic-workflow --lib known_traits_include_every_doc_mirror_trait_def`; `cargo test -p agentic-workflow --test cli_tests root_trait_coverage`'
ASSERTIONS = ('Required outcome for existing-project-standardization:service-workload-profile-derivation: `cargo test -p agentic-workflow --lib stateful_storage_selects_the_statefulset_service_profile`; `cargo test -p agentic-workflow --lib known_traits_include_every_doc_mirror_trait_def`; `cargo test -p agentic-workflow --test cli_tests root_trait_coverage`', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
