"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-active-td-marker-reconciliation-scope'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'active-td-marker-reconciliation-scope'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-active-td-marker-reconciliation-scope'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib marker_gate_scope_prefers_active_td_changes_over_persistent_branch_history -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib marker_gate_scope_prefers_active_td_changes_over_persistent_branch_history -- --nocapture`; terminal marker reconciliation treats explicit active-TD Changes paths as authoritative, so persistent branch history cannot make foreign HANDWRITE markers block an unrelated work item'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:active-td-marker-reconciliation-scope: `cargo test -p agentic-workflow --lib marker_gate_scope_prefers_active_td_changes_over_persistent_branch_history -- --nocapture`; terminal marker reconciliation treats explicit active-TD Changes paths as authoritative, so persistent branch history cannot make foreign HANDWRITE markers block an unrelated work item', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
