"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-ec-independent-agent-review'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'ec-independent-agent-review'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-ec-independent-agent-review'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ec_review_ -- --nocapture', 'cargo test -p agentic-workflow --lib terminal_ec_missing_semantic_review_routes_to_hitl -- --nocapture')
REFERENCE_TOKENS = ('ec_review_backing', 'human')
CLAIM_ORACLE = "`cargo test -p agentic-workflow --lib ec_review_ -- --nocapture`; `cargo test -p agentic-workflow --lib terminal_ec_missing_semantic_review_routes_to_hitl -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-ec-only-semantic-approval.md; apps/agentic-workflow/tech-design/surface/specs/aw-ec-agent-review-protocol.md; a project's `ec_review_backing` policy (`human` default \\"
ASSERTIONS = ("Required outcome for project-local-td-and-ec-gates:ec-independent-agent-review: `cargo test -p agentic-workflow --lib ec_review_ -- --nocapture`; `cargo test -p agentic-workflow --lib terminal_ec_missing_semantic_review_routes_to_hitl -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-ec-only-semantic-approval.md; apps/agentic-workflow/tech-design/surface/specs/aw-ec-agent-review-protocol.md; a project's `ec_review_backing` policy (`human` default \\", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
