"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-typed-agent-prompt-contract'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'typed-agent-prompt-contract'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-typed-agent-prompt-contract'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::llm::tests::prompt_topic_public_renderer_pins_closed_language -- --exact --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = 'three-change roadmap delivered by #2439 vocabulary/grammar, #2440 typed IR/envelope, and #2441 lifecycle migration/conformance'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:typed-agent-prompt-contract: three-change roadmap delivered by #2439 vocabulary/grammar, #2440 typed IR/envelope, and #2441 lifecycle migration/conformance', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
