"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-td-generation-project-root-precedence'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'td-generation-project-root-precedence'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-td-generation-project-root-precedence'
TARGET_COMMANDS = ('cargo test -p agentic-workflow td_gen_prefers_issue_scope_over_foreign_legacy_discovery --lib -- --nocapture',)
REFERENCE_TOKENS = ('.aw/tech-design',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow td_gen_prefers_issue_scope_over_foreign_legacy_discovery --lib -- --nocapture`; a hydrated project-labelled issue selects its configured project TD root before foreign legacy `.aw/tech-design` discovery'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:td-generation-project-root-precedence: `cargo test -p agentic-workflow td_gen_prefers_issue_scope_over_foreign_legacy_discovery --lib -- --nocapture`; a hydrated project-labelled issue selects its configured project TD root before foreign legacy `.aw/tech-design` discovery', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
