"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-xml-adoption-source-diff-guard'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'xml-adoption-source-diff-guard'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-xml-adoption-source-diff-guard'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test cli_tests cb_fill_test::test_apply_commits_current_marker_and_preserves_unrelated_dirty_path -- --nocapture',)
REFERENCE_TOKENS = ('aw cb fill <id> --apply',)
CLAIM_ORACLE = "`cargo test -p agentic-workflow --test cli_tests cb_fill_test::test_apply_commits_current_marker_and_preserves_unrelated_dirty_path -- --nocapture`; `aw cb fill <id> --apply` commits only the active marker's declared source path while preserving unrelated dirty work untouched in the worktree"
ASSERTIONS = ("Required outcome for td-cb-lifecycle-automation:xml-adoption-source-diff-guard: `cargo test -p agentic-workflow --test cli_tests cb_fill_test::test_apply_commits_current_marker_and_preserves_unrelated_dirty_path -- --nocapture`; `aw cb fill <id> --apply` commits only the active marker's declared source path while preserving unrelated dirty work untouched in the worktree", 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
