"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-canonical-epic-change-wi-taxonomy'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'canonical-epic-change-wi-taxonomy'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-canonical-epic-change-wi-taxonomy'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test wi_epic_change_taxonomy_cli_test -- --nocapture', 'cargo test -p agentic-workflow --lib legacy_non_epic_ -- --nocapture', 'cargo test -p agentic-workflow --lib parse_gh_issue_normalizes_legacy_types_without_mutating_labels -- --nocapture', 'cargo test -p agentic-workflow --lib parse_glab_issue_normalizes_legacy_types_without_mutating_labels -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test wi_epic_change_taxonomy_cli_test -- --nocapture`; `cargo test -p agentic-workflow --lib legacy_non_epic_ -- --nocapture`; `cargo test -p agentic-workflow --lib parse_gh_issue_normalizes_legacy_types_without_mutating_labels -- --nocapture`; `cargo test -p agentic-workflow --lib parse_glab_issue_normalizes_legacy_types_without_mutating_labels -- --nocapture`; public authoring and output use only epic/change, while local/GitHub/GitLab compatibility reads preserve legacy labels and identity without mutation'
ASSERTIONS = ('Required outcome for work-item-planning:canonical-epic-change-wi-taxonomy: `cargo test -p agentic-workflow --test wi_epic_change_taxonomy_cli_test -- --nocapture`; `cargo test -p agentic-workflow --lib legacy_non_epic_ -- --nocapture`; `cargo test -p agentic-workflow --lib parse_gh_issue_normalizes_legacy_types_without_mutating_labels -- --nocapture`; `cargo test -p agentic-workflow --lib parse_glab_issue_normalizes_legacy_types_without_mutating_labels -- --nocapture`; public authoring and output use only epic/change, while local/GitHub/GitLab compatibility reads preserve legacy labels and identity without mutation', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
