"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-app-lib-handwrite-marker-discovery'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'app-lib-handwrite-marker-discovery'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-app-lib-handwrite-marker-discovery'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test cli_tests test_apply_marker_replaces_block -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test cli_tests test_apply_marker_replaces_block -- --nocapture`; whole-worktree marker discovery covers app and library roots while active fill stays scoped to declared Changes paths'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:app-lib-handwrite-marker-discovery: `cargo test -p agentic-workflow --test cli_tests test_apply_marker_replaces_block -- --nocapture`; whole-worktree marker discovery covers app and library roots while active fill stays scoped to declared Changes paths', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
