"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-python-reference-http-db'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'python-reference-http-db'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-python-reference-http-db'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test python_spec_http_db_fixture -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test python_spec_http_db_fixture -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-reference-http-db.md; a DDD FastAPI/Pydantic/SQLAlchemy/SQLite reference demonstrates Python TD boundaries without elevating the reference stack into a framework contract'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:python-reference-http-db: `cargo test -p agentic-workflow --test python_spec_http_db_fixture -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/python-reference-http-db.md; a DDD FastAPI/Pydantic/SQLAlchemy/SQLite reference demonstrates Python TD boundaries without elevating the reference stack into a framework contract', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
