"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-stale-ec-inventory-verifier-fail-closed-routing'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'stale-ec-inventory-verifier-fail-closed-routing'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-stale-ec-inventory-verifier-fail-closed-routing'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ec_verify_refuses_stale_inventory_before_running_commands -- --nocapture', 'cargo test -p agentic-workflow --lib ec_verify_routes_missing_semantic_review_before_running_commands -- --nocapture')
REFERENCE_TOKENS = ('td gen',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib ec_verify_refuses_stale_inventory_before_running_commands -- --nocapture`; `cargo test -p agentic-workflow --lib ec_verify_routes_missing_semantic_review_before_running_commands -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; EC verify refuses stale or unreviewed generated inventories before command execution and routes root-owned WIs to independent EC review/regeneration instead of an unrunnable cb_filled `td gen` loop'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:stale-ec-inventory-verifier-fail-closed-routing: `cargo test -p agentic-workflow --lib ec_verify_refuses_stale_inventory_before_running_commands -- --nocapture`; `cargo test -p agentic-workflow --lib ec_verify_routes_missing_semantic_review_before_running_commands -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; EC verify refuses stale or unreviewed generated inventories before command execution and routes root-owned WIs to independent EC review/regeneration instead of an unrunnable cb_filled `td gen` loop', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
