"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-existing-xml-handwrite-adoption'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'existing-xml-handwrite-adoption'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-existing-xml-handwrite-adoption'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib adopt_existing_ -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib adopt_existing_ -- --nocapture`; existing implementations enclosed by pending XML markers use an explicit adoption payload that preserves the body and binds it to the owning work item'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:existing-xml-handwrite-adoption: `cargo test -p agentic-workflow --lib adopt_existing_ -- --nocapture`; existing implementations enclosed by pending XML markers use an explicit adoption payload that preserves the body and binds it to the owning work item', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
