"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-remote-wi-create-authoring-continuity'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'remote-wi-create-authoring-continuity'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-remote-wi-create-authoring-continuity'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test wi_create_remote_lifecycle_test -- --nocapture',)
REFERENCE_TOKENS = ('aw.cli.v1',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test wi_create_remote_lifecycle_test -- --nocapture`; configured remote creation mirrors the canonical tracker id into workspace lifecycle state, the accepted fill is projected back to the tracker before validation, and validation terminates with an executable `aw.cli.v1` done envelope'
ASSERTIONS = ('Required outcome for work-item-planning:remote-wi-create-authoring-continuity: `cargo test -p agentic-workflow --test wi_create_remote_lifecycle_test -- --nocapture`; configured remote creation mirrors the canonical tracker id into workspace lifecycle state, the accepted fill is projected back to the tracker before validation, and validation terminates with an executable `aw.cli.v1` done envelope', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
