"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-digest-bound-project-planning-transaction'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'digest-bound-project-planning-transaction'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-digest-bound-project-planning-transaction'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib planning_transaction::tests -- --nocapture', 'cargo test -p agentic-workflow --test wi_project_plan_transaction_cli_test -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib planning_transaction::tests -- --nocapture`; `cargo test -p agentic-workflow --test wi_project_plan_transaction_cli_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/project-plan-transaction.md; accepted project-plan review binds the exact tracker snapshot and ordered mutation manifest, fails drift before writes, preserves duplicate/superseded history, and retries through tracker idempotency markers without duplicate issues'
ASSERTIONS = ('Required outcome for work-item-planning:digest-bound-project-planning-transaction: `cargo test -p agentic-workflow --lib planning_transaction::tests -- --nocapture`; `cargo test -p agentic-workflow --test wi_project_plan_transaction_cli_test -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/project-plan-transaction.md; accepted project-plan review binds the exact tracker snapshot and ordered mutation manifest, fails drift before writes, preserves duplicate/superseded history, and retries through tracker idempotency markers without duplicate issues', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
