"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-default-td-target-plan-queue'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'default-td-target-plan-queue'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-default-td-target-plan-queue'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib target_plan -- --nocapture', 'cargo test -p agentic-workflow --test cli_tests td_create_default_changes_queue_applies_both_passes_then_gen_uses_explicit_target -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib target_plan -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests td_create_default_changes_queue_applies_both_passes_then_gen_uses_explicit_target -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; fresh TD applicability and contract passes dispatch an editable Logic -> Changes -> Unit Test queue whose explicit target plan reaches code generation'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:default-td-target-plan-queue: `cargo test -p agentic-workflow --lib target_plan -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests td_create_default_changes_queue_applies_both_passes_then_gen_uses_explicit_target -- --nocapture`; apps/agentic-workflow/tech-design/semantic/agentic-workflow-cli.md; fresh TD applicability and contract passes dispatch an editable Logic -> Changes -> Unit Test queue whose explicit target plan reaches code generation', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
