"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-workflow-root-runner-python-artifact-goal-flow'
CAPABILITY_ID = 'workflow-root-runner'
USE_CASE_ID = 'python-artifact-goal-flow'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-workflow-root-runner-python-artifact-goal-flow'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib python_artifact_goal_routing_ -- --nocapture',)
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib python_artifact_goal_routing_ -- --nocapture`; apps/agentic-workflow/tech-design/logic/aw-python-artifact-goal-flow.md; every project follows the EC-first Python progression from direct EC check through TD compilation, target generation, CB checks, and terminal EC verification'
ASSERTIONS = ('Required outcome for workflow-root-runner:python-artifact-goal-flow: `cargo test -p agentic-workflow --lib python_artifact_goal_routing_ -- --nocapture`; apps/agentic-workflow/tech-design/logic/aw-python-artifact-goal-flow.md; every project follows the EC-first Python progression from direct EC check through TD compilation, target generation, CB checks, and terminal EC verification', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
