"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-project-local-td-and-ec-gates-canonical-python-self-hosting-ec-inventory'
CAPABILITY_ID = 'project-local-td-and-ec-gates'
USE_CASE_ID = 'canonical-python-self-hosting-ec-inventory'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-project-local-td-and-ec-gates-canonical-python-self-hosting-ec-inventory'
TARGET_COMMANDS = ('python3 apps/agentic-workflow/external-contracts/src/inventory_parity.py',)
REFERENCE_TOKENS = ('./target/debug/aw ec check --project agentic-workflow --json',)
CLAIM_ORACLE = '`python3 apps/agentic-workflow/external-contracts/src/inventory_parity.py`; `./target/debug/aw ec check --project agentic-workflow --json`; apps/agentic-workflow/external-contracts/pyproject.toml; all 98 legacy case identities and coverage bindings are retained by ordinary Python modules, two stale compatibility oracles are explicitly corrected to the canonical Python scaffold and current integration-test target, and 14 operational cases close the required efficiency/stability dimensions for every DeveloperTool capability through measured, repeatable external commands and non-empty per-case staged evidence'
ASSERTIONS = ('Required outcome for project-local-td-and-ec-gates:canonical-python-self-hosting-ec-inventory: `python3 apps/agentic-workflow/external-contracts/src/inventory_parity.py`; `./target/debug/aw ec check --project agentic-workflow --json`; apps/agentic-workflow/external-contracts/pyproject.toml; all 98 legacy case identities and coverage bindings are retained by ordinary Python modules, two stale compatibility oracles are explicitly corrected to the canonical Python scaffold and current integration-test target, and 14 operational cases close the required efficiency/stability dimensions for every DeveloperTool capability through measured, repeatable external commands and non-empty per-case staged evidence', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
