"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-td-cb-lifecycle-automation-markerless-hand-written-td-generation-guard'
CAPABILITY_ID = 'td-cb-lifecycle-automation'
USE_CASE_ID = 'markerless-hand-written-td-generation-guard'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-td-cb-lifecycle-automation-markerless-hand-written-td-generation-guard'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib hand_written_existing_target_requires_anchor_before_lifecycle_progress -- --nocapture',)
REFERENCE_TOKENS = ('anchor:',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib hand_written_existing_target_requires_anchor_before_lifecycle_progress -- --nocapture`; existing hand-written targets require a valid TD `anchor:` so AW scaffolds a bounded HANDWRITE payload before lifecycle progress'
ASSERTIONS = ('Required outcome for td-cb-lifecycle-automation:markerless-hand-written-td-generation-guard: `cargo test -p agentic-workflow --lib hand_written_existing_target_requires_anchor_before_lifecycle_progress -- --nocapture`; existing hand-written targets require a valid TD `anchor:` so AW scaffolds a bounded HANDWRITE payload before lifecycle progress', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
