"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-workflow-root-runner-python-only-artifact-model-routing'
CAPABILITY_ID = 'workflow-root-runner'
USE_CASE_ID = 'python-only-artifact-model-routing'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-workflow-root-runner-python-only-artifact-model-routing'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib python_artifact_goal_routing_ -- --nocapture', 'cargo test -p agentic-workflow --test artifact_model_config_test --test ec_python_inventory_check --test python_artifact_readiness')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib python_artifact_goal_routing_ -- --nocapture`; `cargo test -p agentic-workflow --test artifact_model_config_test --test ec_python_inventory_check --test python_artifact_readiness`; omitted and explicit legacy values resolve to Python, and stale legacy tracker phases restart at EC-first Python authoring rather than section-payload TD'
ASSERTIONS = ('Required outcome for workflow-root-runner:python-only-artifact-model-routing: `cargo test -p agentic-workflow --lib python_artifact_goal_routing_ -- --nocapture`; `cargo test -p agentic-workflow --test artifact_model_config_test --test ec_python_inventory_check --test python_artifact_readiness`; omitted and explicit legacy values resolve to Python, and stale legacy tracker phases restart at EC-first Python authoring rather than section-payload TD', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
