"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-ownership-matrix'
CAPABILITY_ID = 'aw-core-client-model-workitem-first-artifact-lifecycle'
USE_CASE_ID = 'meta-doc-ownership-matrix'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-aw-core-client-model-workitem-first-artifact-lifecycle-meta-doc-ownership-matrix'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib meta_doc_ownership -- --nocapture', 'cargo test -p agentic-workflow --test cli_tests root_doc_ -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib meta_doc_ownership -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests root_doc_ -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-meta-doc-ownership-matrix.md; one serializable repo/project matrix drives placement, required headings, inheritance documentation, root allowlists, and actionable project-agent-doc diagnostics'
ASSERTIONS = ('Required outcome for aw-core-client-model-workitem-first-artifact-lifecycle:meta-doc-ownership-matrix: `cargo test -p agentic-workflow --lib meta_doc_ownership -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests root_doc_ -- --nocapture`; apps/agentic-workflow/tech-design/surface/specs/aw-meta-doc-ownership-matrix.md; one serializable repo/project matrix drives placement, required headings, inheritance documentation, root allowlists, and actionable project-agent-doc diagnostics', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
