"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-work-item-planning-issue-platform-epic-change-graph-invariants'
CAPABILITY_ID = 'work-item-planning'
USE_CASE_ID = 'issue-platform-epic-change-graph-invariants'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-work-item-planning-issue-platform-epic-change-graph-invariants'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --test wi_epic_change_graph_cli_test -- --nocapture', 'cargo test -p agentic-workflow --lib issues::graph::tests -- --nocapture')
REFERENCE_TOKENS = ('aw wi graph',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --test wi_epic_change_graph_cli_test -- --nocapture`; `cargo test -p agentic-workflow --lib issues::graph::tests -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/epic-change-graph.md; `aw wi graph` projects deterministic ownership, priority inheritance, dependency, duplicate, and sibling-supersession state without tracker writes and fails closed on invalid open-change ownership'
ASSERTIONS = ('Required outcome for work-item-planning:issue-platform-epic-change-graph-invariants: `cargo test -p agentic-workflow --test wi_epic_change_graph_cli_test -- --nocapture`; `cargo test -p agentic-workflow --lib issues::graph::tests -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/epic-change-graph.md; `aw wi graph` projects deterministic ownership, priority inheritance, dependency, duplicate, and sibling-supersession state without tracker writes and fails closed on invalid open-change ownership', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
