"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-existing-project-standardization-structured-observability-and-raft-telemetry-conformance-rules'
CAPABILITY_ID = 'existing-project-standardization'
USE_CASE_ID = 'structured-observability-and-raft-telemetry-conformance-rules'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-existing-project-standardization-structured-observability-and-raft-telemetry-conformance-rules'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::review_obs_rules', 'cargo test -p agentic-workflow --lib cli::review')
REFERENCE_TOKENS = ('./target/debug/aw review --project agentic-workflow --pretty',)
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::review_obs_rules`; `cargo test -p agentic-workflow --lib cli::review`; `./target/debug/aw review --project agentic-workflow --pretty`; apps/agentic-workflow/tech-design/validate/aw-review-structured-observability-raft-telemetry-conformance-ru.md'
ASSERTIONS = ('Required outcome for existing-project-standardization:structured-observability-and-raft-telemetry-conformance-rules: `cargo test -p agentic-workflow --lib cli::review_obs_rules`; `cargo test -p agentic-workflow --lib cli::review`; `./target/debug/aw review --project agentic-workflow --pretty`; apps/agentic-workflow/tech-design/validate/aw-review-structured-observability-raft-telemetry-conformance-ru.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
