"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-workflow-root-runner-prioritized-reviewed-graph-goal-selection'
CAPABILITY_ID = 'workflow-root-runner'
USE_CASE_ID = 'prioritized-reviewed-graph-goal-selection'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-workflow-root-runner-prioritized-reviewed-graph-goal-selection'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib ready_graph::tests -- --nocapture', 'cargo test -p agentic-workflow --test wi_reviewed_graph_goal_cli_test -- --nocapture', 'cargo test -p agentic-workflow --test cli_tests goal_backlog -- --nocapture')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib ready_graph::tests -- --nocapture`; `cargo test -p agentic-workflow --test wi_reviewed_graph_goal_cli_test -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests goal_backlog -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/reviewed-graph-goal-selection.md; epic and backlog roots consume the same accepted published graph, choose epic priority before ready child priority, park blocked leaves, roll terminal epics up, and fail closed on stale or invalid graph metadata without re-atomizing'
ASSERTIONS = ('Required outcome for workflow-root-runner:prioritized-reviewed-graph-goal-selection: `cargo test -p agentic-workflow --lib ready_graph::tests -- --nocapture`; `cargo test -p agentic-workflow --test wi_reviewed_graph_goal_cli_test -- --nocapture`; `cargo test -p agentic-workflow --test cli_tests goal_backlog -- --nocapture`; apps/agentic-workflow/tech-design/core/logic/issues/reviewed-graph-goal-selection.md; epic and backlog roots consume the same accepted published graph, choose epic priority before ready child priority, park blocked leaves, roll terminal epics up, and fail closed on stale or invalid graph metadata without re-atomizing', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
