"""Generated ordinary Python EC declaration for one required capability claim."""

# Generated by src/claim_reconciliation.py; semantic acceptance requires independent EC review.
CASE_ID = 'claim-closure-existing-project-standardization-shared-service-kit-conformance-rules'
CAPABILITY_ID = 'existing-project-standardization'
USE_CASE_ID = 'shared-service-kit-conformance-rules'
DIMENSION = 'behavior'
TARGET_COMMAND = 'python3 apps/agentic-workflow/external-contracts/src/claim_gate.py --case claim-closure-existing-project-standardization-shared-service-kit-conformance-rules'
TARGET_COMMANDS = ('cargo test -p agentic-workflow --lib cli::review_rules', 'cargo test -p agentic-workflow --lib cli::review')
REFERENCE_TOKENS = ()
CLAIM_ORACLE = '`cargo test -p agentic-workflow --lib cli::review_rules`; `cargo test -p agentic-workflow --lib cli::review`; apps/agentic-workflow/tech-design/config/aw-review-shared-service-kit-adoption-rules-profile-negative-ass.md'
ASSERTIONS = ('Required outcome for existing-project-standardization:shared-service-kit-conformance-rules: `cargo test -p agentic-workflow --lib cli::review_rules`; `cargo test -p agentic-workflow --lib cli::review`; apps/agentic-workflow/tech-design/config/aw-review-shared-service-kit-adoption-rules-profile-negative-ass.md', 'Every declared executable gate runs successfully; cargo test selectors must execute at least one test.')
