//! GENERATED by tests/harness/cpython/tools/type_wall_gen.py --emit-rust.
//! DO NOT EDIT BY HAND.
//!
//! schema: 2  branches: 15712  py312: 14137
//! params: 43370  type-params: 416
//! aliases: 415
//! classes: 3077  class-exports: 3807
//! class-method-edges: 12866
//! callable-exports: 3717
//! class-callables: 13195
//! type-nodes: 8244  type-edges: 12484

pub const MANIFEST_JSON: &str = include_str!("stdlib_specs_generated.json");
