//! GENERATED by tests/harness/cpython/tools/type_wall_gen.py --emit-rust.
//! DO NOT EDIT BY HAND.
//!
//! schema: 1  branches: 15712  py312: 14137
//! params: 40818  type-params: 419
//! aliases: 445
//! type-nodes: 7073  type-edges: 8566

pub const MANIFEST_JSON: &str = include_str!("stdlib_specs_generated.json");
