//! GENERATED by tests/harness/cpython/tools/type_wall_gen.py --emit-rust.
//! DO NOT EDIT BY HAND. Reproduce with:
//!   python3.12 tests/harness/cpython/tools/checkout_typeshed.py
//!   python3.12 tests/harness/cpython/tools/type_wall_gen.py --emit-rust
//!
//! typeshed-repository: https://github.com/python/typeshed.git
//! typeshed-revision: a7bcce8b6df32dd85dc31691cef30af61e7b1371
//! typeshed-stdlib-pyi-count: 752
//! typeshed-stdlib-pyi-sha256: b616692e13744897bea61d69ec9918104df2ad657ede10ced27182eefde34fd1
//!
//! schema: 2  branches: 15711  py312: 14136
//! params: 43369  type-params: 416
//! aliases: 415
//! classes: 3077  class-exports: 3807
//! class-method-edges: 12865
//! callable-exports: 3717
//! class-callables: 13194
//! type-nodes: 7867  type-edges: 12245

pub const MANIFEST_JSON: &str = include_str!("stdlib_specs_generated.json");
