use super::c_types::*;
use super::type_map;
use crate::types::context::TypeContext;
use crate::types::ty::Ty;

/// Generate a .tpi stub file from a C header (#260).
pub fn generate_tpi_stub(header: &CHeader, module_name: &str) -> String {
    let mut tcx = TypeContext::new();
    let mut out = String::new();
    out.push_str(&format!("# {module_name}.tpi — auto-generated by mamba\n\n"));

    // Generate class stubs for structs
    for s in &header.structs {
        out.push_str(&format!("class {}:\n", s.name));
        for field in &s.fields {
            let ty = type_map::c_type_to_mamba(&field.ty, &mut tcx);
            let ty_name = mamba_type_name(&tcx, ty);
            out.push_str(&format!("    {}: {}\n", field.name, ty_name));
        }
        // Add constructor
        out.push_str("    def __init__(self");
        for field in &s.fields {
            let ty = type_map::c_type_to_mamba(&field.ty, &mut tcx);
            let ty_name = mamba_type_name(&tcx, ty);
            out.push_str(&format!(", {}: {}", field.name, ty_name));
        }
        out.push_str(") -> None: ...\n\n");
    }

    // Generate enum class stubs
    for e in &header.enums {
        out.push_str(&format!("class {}:\n", e.name));
        for v in &e.variants {
            let clean = clean_variant_display(&v.name, &e.name);
            let val = v.value.unwrap_or(0);
            out.push_str(&format!("    {clean}: int = {val}\n"));
        }
        out.push('\n');
    }

    // Generate function stubs
    for f in &header.functions {
        out.push_str("def ");
        out.push_str(&f.name);
        out.push('(');
        for (i, param) in f.params.iter().enumerate() {
            if i > 0 { out.push_str(", "); }
            let ty = type_map::c_type_to_mamba(&param.ty, &mut tcx);
            let ty_name = mamba_type_name(&tcx, ty);
            out.push_str(&format!("{}: {}", param.name, ty_name));
        }
        let ret_ty = type_map::c_type_to_mamba(&f.return_type, &mut tcx);
        let ret_name = mamba_type_name(&tcx, ret_ty);
        out.push_str(&format!(") -> {ret_name}: ...\n"));
    }

    out
}

fn mamba_type_name(tcx: &TypeContext, ty_id: crate::types::ty::TypeId) -> String {
    match tcx.get(ty_id) {
        Ty::Never => "Never".into(),
        Ty::None => "None".into(),
        Ty::Bool => "bool".into(),
        Ty::Int => "int".into(),
        Ty::Float => "float".into(),
        Ty::Str => "str".into(),
        Ty::Any => "Any".into(),
        Ty::Class { name, .. } => name.clone(),
        Ty::Union(ts) if ts.len() == 2 => {
            // Check for Optional (T | None)
            let t0 = mamba_type_name(tcx, ts[0]);
            let t1 = mamba_type_name(tcx, ts[1]);
            if t1 == "None" {
                format!("{t0}?")
            } else {
                format!("{t0} | {t1}")
            }
        }
        _ => "Any".into(),
    }
}

fn clean_variant_display(variant: &str, enum_name: &str) -> String {
    let stripped = if variant.starts_with(enum_name) {
        &variant[enum_name.len()..]
    } else {
        variant
    };
    let stripped = stripped.trim_start_matches('_');
    let mut result = String::new();
    for (i, c) in stripped.chars().enumerate() {
        if c.is_uppercase() && i > 0 { result.push('_'); }
        result.push(c.to_ascii_uppercase());
    }
    if result.is_empty() { variant.to_uppercase() } else { result }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_function_stub() {
        let header = CHeader {
            functions: vec![CFunction {
                name: "add".into(),
                params: vec![
                    CParam { name: "a".into(), ty: CType::Int32 },
                    CParam { name: "b".into(), ty: CType::Int32 },
                ],
                return_type: CType::Int32,
            }],
            structs: vec![],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "math");
        assert!(stub.contains("def add(a: int, b: int) -> int: ..."));
    }

    #[test]
    fn test_generate_struct_stub() {
        let header = CHeader {
            functions: vec![],
            structs: vec![CStruct {
                name: "Point".into(),
                fields: vec![
                    CField { name: "x".into(), ty: CType::Int32 },
                    CField { name: "y".into(), ty: CType::Int32 },
                ],
            }],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "geo");
        assert!(stub.contains("class Point:"));
        assert!(stub.contains("x: int"));
        assert!(stub.contains("y: int"));
    }

    // --- Additional tests ---

    #[test]
    fn test_generate_empty_header() {
        let header = CHeader::default();
        let stub = generate_tpi_stub(&header, "empty");
        assert!(stub.contains("# empty.tpi"));
        // Should not contain class or def declarations
        assert!(!stub.contains("class "));
        assert!(!stub.contains("def "));
    }

    #[test]
    fn test_generate_module_header_comment() {
        let header = CHeader::default();
        let stub = generate_tpi_stub(&header, "my_module");
        assert!(stub.starts_with("# my_module.tpi"));
        assert!(stub.contains("auto-generated by mamba"));
    }

    #[test]
    fn test_generate_void_function() {
        let header = CHeader {
            functions: vec![CFunction {
                name: "init".into(),
                params: vec![],
                return_type: CType::Void,
            }],
            structs: vec![],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "lib");
        assert!(stub.contains("def init() -> None: ..."));
    }

    #[test]
    fn test_generate_function_with_float_params() {
        let header = CHeader {
            functions: vec![CFunction {
                name: "distance".into(),
                params: vec![
                    CParam { name: "x".into(), ty: CType::Double },
                    CParam { name: "y".into(), ty: CType::Float },
                ],
                return_type: CType::Double,
            }],
            structs: vec![],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "geo");
        assert!(stub.contains("def distance(x: float, y: float) -> float: ..."));
    }

    #[test]
    fn test_generate_function_with_bool_param() {
        let header = CHeader {
            functions: vec![CFunction {
                name: "set_flag".into(),
                params: vec![
                    CParam { name: "flag".into(), ty: CType::Bool },
                ],
                return_type: CType::Void,
            }],
            structs: vec![],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "cfg");
        assert!(stub.contains("def set_flag(flag: bool) -> None: ..."));
    }

    #[test]
    fn test_generate_function_with_string_param() {
        let header = CHeader {
            functions: vec![CFunction {
                name: "greet".into(),
                params: vec![
                    CParam { name: "name".into(), ty: CType::ConstChar },
                ],
                return_type: CType::Void,
            }],
            structs: vec![],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "io");
        assert!(stub.contains("def greet(name: str) -> None: ..."));
    }

    #[test]
    fn test_generate_struct_with_constructor() {
        let header = CHeader {
            functions: vec![],
            structs: vec![CStruct {
                name: "Vec2".into(),
                fields: vec![
                    CField { name: "x".into(), ty: CType::Float },
                    CField { name: "y".into(), ty: CType::Float },
                ],
            }],
            enums: vec![],
        };
        let stub = generate_tpi_stub(&header, "math");
        assert!(stub.contains("class Vec2:"));
        assert!(stub.contains("def __init__(self, x: float, y: float) -> None: ..."));
    }

    #[test]
    fn test_generate_enum_stub() {
        let header = CHeader {
            functions: vec![],
            structs: vec![],
            enums: vec![CEnum {
                name: "Color".into(),
                variants: vec![
                    CEnumVariant { name: "ColorRed".into(), value: Some(0) },
                    CEnumVariant { name: "ColorGreen".into(), value: Some(1) },
                    CEnumVariant { name: "ColorBlue".into(), value: Some(2) },
                ],
            }],
        };
        let stub = generate_tpi_stub(&header, "gfx");
        assert!(stub.contains("class Color:"));
        // Variant names should be cleaned and uppercased
        assert!(stub.contains("int = 0"));
        assert!(stub.contains("int = 1"));
        assert!(stub.contains("int = 2"));
    }

    #[test]
    fn test_generate_enum_default_value() {
        let header = CHeader {
            functions: vec![],
            structs: vec![],
            enums: vec![CEnum {
                name: "Status".into(),
                variants: vec![
                    CEnumVariant { name: "Ok".into(), value: None },
                ],
            }],
        };
        let stub = generate_tpi_stub(&header, "stat");
        // value=None -> defaults to 0
        assert!(stub.contains("int = 0"));
    }

    #[test]
    fn test_generate_multiple_items() {
        let header = CHeader {
            functions: vec![CFunction {
                name: "create".into(),
                params: vec![],
                return_type: CType::Int32,
            }],
            structs: vec![CStruct {
                name: "Obj".into(),
                fields: vec![CField { name: "id".into(), ty: CType::Int32 }],
            }],
            enums: vec![CEnum {
                name: "Kind".into(),
                variants: vec![
                    CEnumVariant { name: "A".into(), value: Some(0) },
                ],
            }],
        };
        let stub = generate_tpi_stub(&header, "multi");
        assert!(stub.contains("class Obj:"));
        assert!(stub.contains("class Kind:"));
        assert!(stub.contains("def create() -> int: ..."));
    }

    #[test]
    fn test_clean_variant_display_prefix_strip() {
        assert_eq!(clean_variant_display("ColorRed", "Color"), "RED");
        assert_eq!(clean_variant_display("StatusOk", "Status"), "OK");
    }

    #[test]
    fn test_clean_variant_display_no_prefix() {
        assert_eq!(clean_variant_display("Blue", "Color"), "BLUE");
    }

    #[test]
    fn test_clean_variant_display_empty_after_strip() {
        // variant == enum_name => stripped is empty => fallback
        assert_eq!(clean_variant_display("Color", "Color"), "COLOR");
    }

    #[test]
    fn test_clean_variant_display_underscore_prefix() {
        assert_eq!(clean_variant_display("Color_Red", "Color"), "RED");
    }
}
