/// Standard library for Mamba (#310, #P2).
///
/// Provides built-in modules registered in the symbol table,
/// with constant attributes pre-loaded.

pub mod sys_mod;
pub mod os_mod;
pub mod math_mod;
pub mod json_mod;
pub mod time_mod;
// P2 stdlib modules
pub mod re_mod;
pub mod datetime_mod;
pub mod collections_mod;
pub mod itertools_mod;
pub mod functools_mod;
pub mod pathlib_mod;
pub mod random_mod;
pub mod shutil_mod;
pub mod tempfile_mod;
pub mod glob_mod;
pub mod io_mod;
pub mod struct_mod;
pub mod hashlib_mod;
pub mod base64_mod;
pub mod decimal_mod;
pub mod fractions_mod;
pub mod contextlib_mod;
pub mod copy_mod;
pub mod copyreg_mod;
pub mod operator_mod;
pub mod weakref_mod;
pub mod traceback_mod;
pub mod warnings_mod;
pub mod inspect_mod;
pub mod enum_mod;
pub mod dataclasses_mod;
// P3 stdlib modules
pub mod subprocess_mod;
pub mod csv_mod;
pub mod argparse_mod;
pub mod logging_mod;
pub mod typing_mod;
pub mod threading_mod;
pub mod socket_mod;
pub mod http_mod;
pub mod unittest_mod;
pub mod unittest_mock_mod;
pub mod pickle_mod;
pub mod sqlite3_mod;
pub mod gzip_mod;
pub mod zipfile_mod;
pub mod tarfile_mod;
pub mod pprint_mod;
pub mod textwrap_mod;
pub mod string_constants_mod;
pub mod xml_mod;
pub mod html_parser_mod;
pub mod array_mod;
pub mod cmath_mod;
pub mod colorsys_mod;
pub mod abc_mod;
pub mod heapq_mod;
pub mod bisect_mod;
pub mod uuid_mod;
pub mod hmac_mod;
pub mod configparser_mod;
pub mod difflib_mod;
pub mod platform_mod;
pub mod shlex_mod;
pub mod locale_mod;
pub mod calendar_mod;
pub mod statistics_mod;
pub mod numbers_mod;
pub mod unicodedata_mod;
pub mod zlib_mod;
pub mod bz2_mod;
pub mod lzma_mod;
pub mod queue_mod;
pub mod signal_mod;
pub mod selectors_mod;
pub mod secrets_mod;
pub mod asyncio_mod;
// P1 stdlib modules
pub mod errno_mod;
pub mod atexit_mod;
pub mod gc_mod;
pub mod types_mod;
pub mod importlib_mod;
pub mod codecs_mod;
pub mod tracemalloc_mod;
pub mod ast_mod;
pub mod dis_mod;
pub mod tokenize_mod;
pub mod future_mod;
pub mod main_mod;
pub mod builtins_mod;
pub mod test_mod;
pub mod support_mod;
pub mod posix_mod;
pub mod keyword_mod;
pub mod stat_mod;
pub mod token_mod;
pub mod fnmatch_mod;
pub mod getopt_mod;
pub mod graphlib_mod;
pub mod linecache_mod;
pub mod idlelib_mod;
pub mod mimetypes_mod;
pub mod ipaddress_mod;
pub mod urllib_error_mod;
pub mod contextvars_mod;
pub mod http_cookies_mod;
pub mod http_cookiejar_mod;
pub mod email_mod;
pub mod multiprocessing_mod;
pub mod typing_extensions_mod;
pub mod pydantic_core_mod;
pub mod pydantic_mod;
pub mod idna_mod;
pub mod httpx_mod;
pub mod aiofiles_mod;
pub mod pytest_mod;
pub mod jinja2_mod;
pub mod certifi_mod;
pub mod fastapi_mod;
pub mod uvicorn_mod;
pub mod starlette_mod;
pub mod protobuf_mod;
pub mod ssl_mod;
pub mod attrs_mod;
pub mod charset_normalizer_mod;
pub mod requests_mod;
pub mod aiohttp_mod;
pub mod cryptography_mod;
pub mod pyopenssl_mod;
pub mod jsonschema_mod;
pub mod marshmallow_mod;
pub mod msgpack_mod;
pub mod orjson_mod;
pub mod boto3_mod;
pub mod botocore_mod;
pub mod s3transfer_mod;
pub mod jmespath_mod;
pub mod azure_core_mod;
pub mod azure_identity_mod;
pub mod azure_storage_blob_mod;
pub mod azure_keyvault_secrets_mod;
pub mod google_api_core_mod;
pub mod google_cloud_storage_mod;
pub mod google_cloud_pubsub_mod;
pub mod googleapis_common_protos_mod;
pub mod grpclib_mod;
pub mod grpcio_mod;
pub mod flask_mod;
pub mod werkzeug_mod;
pub mod gunicorn_mod;
pub mod sqlalchemy_mod;
pub mod alembic_mod;
pub mod pytest_asyncio_mod;
pub mod hypothesis_mod;
pub mod mock_mod;
pub mod redis_mod;
pub mod celery_mod;
pub mod kombu_mod;
pub mod psycopg_mod;
pub mod urllib3_mod;
pub mod tomllib_mod;
pub mod compileall_mod;
pub mod bdb_mod;
pub mod code_mod;
pub mod binascii_mod;
pub mod concurrent_futures_mod;
pub mod dbm_mod;
pub mod sysconfig_mod;
pub mod reprlib_mod;
pub mod quopri_mod;
pub mod posixpath_mod;
pub mod filecmp_mod;
pub mod stringprep_mod;
pub mod netrc_mod;
pub mod cgi_mod;
pub mod ntpath_mod;
pub mod webbrowser_mod;
pub mod readline_mod;
pub mod encodings_mod;
pub mod uu_mod;
pub mod getpass_mod;
pub mod site_mod;
pub mod fileinput_mod;
pub mod wsgiref_mod;
pub mod xmlrpc_mod;
pub mod dev_tools_mod;
pub mod long_tail_mod;
pub mod plistlib_mod;
pub mod long_tail2_mod;
pub mod long_tail3_mod;
pub mod long_tail4_mod;
pub mod thirdparty_shells_mod;

use std::collections::HashMap;
use super::value::MbValue;
use super::module::mb_module_register;

/// Register all standard library modules.
pub fn register_stdlib() {
    sys_mod::register();
    os_mod::register();
    math_mod::register();
    json_mod::register();
    time_mod::register();
    // P2 modules
    re_mod::register();
    datetime_mod::register();
    collections_mod::register();
    itertools_mod::register();
    functools_mod::register();
    pathlib_mod::register();
    random_mod::register();
    shutil_mod::register();
    tempfile_mod::register();
    glob_mod::register();
    io_mod::register();
    struct_mod::register();
    hashlib_mod::register();
    base64_mod::register();
    decimal_mod::register();
    fractions_mod::register();
    contextlib_mod::register();
    copy_mod::register();
    copyreg_mod::register();
    operator_mod::register();
    weakref_mod::register();
    traceback_mod::register();
    warnings_mod::register();
    inspect_mod::register();
    enum_mod::register();
    dataclasses_mod::register();
    // P3 modules
    subprocess_mod::register();
    csv_mod::register();
    argparse_mod::register();
    logging_mod::register();
    typing_mod::register();
    threading_mod::register();
    socket_mod::register();
    // urllib.error must register BEFORE http_mod so that http_mod's urllib
    // umbrella-wiring (which snapshots child-module attrs into a dict) picks
    // up the proper callable class shells from urllib_error_mod rather than
    // the legacy 3-string-stub block previously inlined in http_mod.
    urllib_error_mod::register();
    http_mod::register();
    unittest_mod::register();
    unittest_mod::register_classes();
    unittest_mock_mod::register();
    pickle_mod::register();
    sqlite3_mod::register();
    gzip_mod::register();
    zipfile_mod::register();
    tarfile_mod::register();
    pprint_mod::register();
    textwrap_mod::register();
    string_constants_mod::register();
    xml_mod::register();
    html_parser_mod::register();
    array_mod::register();
    cmath_mod::register();
    colorsys_mod::register();
    // New stdlib modules
    abc_mod::register();
    heapq_mod::register();
    bisect_mod::register();
    uuid_mod::register();
    hmac_mod::register();
    configparser_mod::register();
    difflib_mod::register();
    platform_mod::register();
    shlex_mod::register();
    locale_mod::register();
    calendar_mod::register();
    statistics_mod::register();
    numbers_mod::register();
    unicodedata_mod::register();
    zlib_mod::register();
    bz2_mod::register();
    lzma_mod::register();
    queue_mod::register();
    signal_mod::register();
    selectors_mod::register();
    secrets_mod::register();
    asyncio_mod::register();
    // P1 stdlib modules
    errno_mod::register();
    atexit_mod::register();
    gc_mod::register();
    types_mod::register();
    importlib_mod::register();
    codecs_mod::register();
    tracemalloc_mod::register();
    ast_mod::register();
    dis_mod::register();
    tokenize_mod::register();
    future_mod::register();
    main_mod::register();
    builtins_mod::register();
    test_mod::register();
    // Behavior augmentation for test.support — MUST run after test_mod::register()
    // (it mutates the already-registered test.support* modules in place).
    support_mod::register();
    posix_mod::register();
    keyword_mod::register();
    stat_mod::register();
    token_mod::register();
    fnmatch_mod::register();
    getopt_mod::register();
    graphlib_mod::register();
    linecache_mod::register();
    idlelib_mod::register();
    mimetypes_mod::register();
    ipaddress_mod::register();
    contextvars_mod::register();
    // http.cookies override must run AFTER http_mod::register() so the
    // callable class-shell surface replaces the legacy non-callable
    // string-stub block. See projects/mamba/src/runtime/stdlib/http_cookies_mod.rs.
    http_cookies_mod::register();
    // http.cookiejar override must run AFTER http_mod::register() for the
    // same dotted-name override reason. See
    // projects/mamba/src/runtime/stdlib/http_cookiejar_mod.rs.
    http_cookiejar_mod::register();
    email_mod::register();
    multiprocessing_mod::register();
    typing_extensions_mod::register();
    pydantic_core_mod::register();
    pydantic_mod::register();
    idna_mod::register();
    httpx_mod::register();
    aiofiles_mod::register();
    pytest_mod::register();
    jinja2_mod::register();
    certifi_mod::register();
    fastapi_mod::register();
    uvicorn_mod::register();
    starlette_mod::register();
    protobuf_mod::register();
    ssl_mod::register();
    attrs_mod::register();
    charset_normalizer_mod::register();
    requests_mod::register();
    aiohttp_mod::register();
    cryptography_mod::register();
    pyopenssl_mod::register();
    jsonschema_mod::register();
    marshmallow_mod::register();
    msgpack_mod::register();
    orjson_mod::register();
    boto3_mod::register();
    botocore_mod::register();
    s3transfer_mod::register();
    jmespath_mod::register();
    azure_core_mod::register();
    azure_identity_mod::register();
    azure_storage_blob_mod::register();
    azure_keyvault_secrets_mod::register();
    google_api_core_mod::register();
    google_cloud_storage_mod::register();
    google_cloud_pubsub_mod::register();
    googleapis_common_protos_mod::register();
    grpclib_mod::register();
    grpcio_mod::register();
    flask_mod::register();
    werkzeug_mod::register();
    gunicorn_mod::register();
    sqlalchemy_mod::register();
    alembic_mod::register();
    pytest_asyncio_mod::register();
    hypothesis_mod::register();
    mock_mod::register();
    redis_mod::register();
    celery_mod::register();
    kombu_mod::register();
    psycopg_mod::register();
    urllib3_mod::register();
    tomllib_mod::register();
    compileall_mod::register();
    bdb_mod::register();
    code_mod::register();
    binascii_mod::register();
    concurrent_futures_mod::register();
    dbm_mod::register();
    sysconfig_mod::register();
    reprlib_mod::register();
    quopri_mod::register();
    posixpath_mod::register();
    filecmp_mod::register();
    stringprep_mod::register();
    netrc_mod::register();
    cgi_mod::register();
    ntpath_mod::register();
    webbrowser_mod::register();
    readline_mod::register();
    encodings_mod::register();
    uu_mod::register();
    getpass_mod::register();
    site_mod::register();
    fileinput_mod::register();
    wsgiref_mod::register();
    xmlrpc_mod::register();
    dev_tools_mod::register();
    long_tail_mod::register();
    plistlib_mod::register();
    long_tail2_mod::register();
    long_tail3_mod::register();
    long_tail4_mod::register();
    thirdparty_shells_mod::register();
}

/// Helper: create a module with given attributes.
pub(crate) fn register_module(name: &str, attrs: HashMap<String, MbValue>) {
    mb_module_register(name, attrs);
}
