apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: loom

labels:
  - pairs:
      app.kubernetes.io/name: loom
      app.kubernetes.io/part-of: loom
    includeSelectors: false

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - pdb.yaml
