steps:
  - id: tape
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=benchmarks/gcp-operator-acceptance/images/Dockerfile.tape
      - --tag=${_REGISTRY}/tape:${_TAG}
      - .

images:
  - ${_REGISTRY}/tape:${_TAG}

timeout: 2700s

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
