[package]
name = "axiom-client-transport-policy-example"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cclab-openapi-codegen = { path = "../../libs/openapi-codegen" }
h2c = { path = "../../libs/h2c" }
lumen = { path = "../../projects/lumen" }
reqwest.workspace = true
service-http = { path = "../../libs/service-http" }
tokio.workspace = true
