steps:
  - id: rig
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=acceptance/gcp/images/Dockerfile.rig
      - --tag=${_REGISTRY}/rig:${_TAG}
      - .

images:
  - ${_REGISTRY}/rig:${_TAG}

tags:
  - axiom-gcp-operator-acceptance
  - axiom-run-${_RUN_ID}

timeout: 2700s

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
