// `uv export` / `uv pip compile`-style requirements.txt synthesis (Tick 41).
//
// Pure data layer: turns a `Lockfile` into a deterministic PEP 508-shaped
// `requirements.txt` body. The caller is responsible for I/O; this module
// holds no side effects.
//
// Mirrors uv's `export --format requirements-txt` surface:
//   * pinned `name==version` lines, sorted alphabetically.
//   * Optional `--hash=sha256:<hex>` continuations (`--hashes`).
//   * Optional autogenerated header banner (`--header` / `--no-header`).
//   * `--no-emit-package` exclusion list.
//   * Non-registry sources rendered as PEP 508 direct-URL requirements:
//       Git    → `name @ git+<url>@<rev>`
//       Path   → `name @ file://<absolute-path>`
//
// Tick 67 (added) — `--annotate` reverse-dep `# via X` comments
// derived from each Package's `dependencies` vec. uv emits these to
// help reviewers understand WHY a pin exists. We compute the reverse
// adjacency once per export and emit `# via <names>` (sorted, PEP 503
// normalized for matching, original casing preserved for display)
// underneath each pin.
//
// What this module still does NOT cover (deferred follow-ups):
//   * Extras filtering / `--all-extras` / `--dev` cohort — needs the
//     dep-group + extras data layer not yet wired into the lockfile.
//   * `--no-emit-project` (workspace-self exclusion) — the lockfile
//     doesn't yet distinguish the workspace root package; layered in
//     when workspace metadata becomes lockfile-resident.

use std::collections::BTreeMap;

use crate::pkgmanage::pkgmgr::lockfile::{Lockfile, Package, SourceRefKind};
use crate::pkgmanage::pkgmgr::name_normalize::pep503_normalize;

/// Caller-tunable rendering knobs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportOptions {
    /// Emit `--hash=sha256:<hex>` continuation lines after each pin.
    pub include_hashes: bool,
    /// Emit the leading `# This file was autogenerated by mamba ...` banner.
    pub include_header: bool,
    /// PEP 503-style names to skip (case-folded, normalized). Empty by default.
    pub exclude_packages: Vec<String>,
    /// Optional marker stamped onto every pin (e.g. `; python_version >= "3.10"`).
    /// `None` means no marker is appended.
    pub global_marker: Option<String>,
    /// Emit `    # via <names>` annotations after each pin showing
    /// which other packages depend on it. Reverse adjacency is computed
    /// from each Package's `dependencies` vec. Roots (no reverse deps)
    /// receive no annotation. Names within one annotation are sorted
    /// PEP 503-normalized and comma-separated. Disabled by default to
    /// keep output minimal.
    pub annotate: bool,
}

impl Default for ExportOptions {
    fn default() -> Self {
        ExportOptions {
            include_hashes: true,
            include_header: true,
            exclude_packages: Vec::new(),
            global_marker: None,
            annotate: false,
        }
    }
}

/// Header text emitted at the top of the file when `include_header` is true.
/// Stable across runs so the body is byte-identical when inputs match.
pub const HEADER: &str = "\
# This file was autogenerated by mamba pkgmgr's `requirements_export`.
# It is intended to be committed into your repository so that downstream
# tools (pip, pip-sync, etc.) can install exactly the resolved graph.
# To regenerate, re-run the export command.
";

/// Render a `Lockfile` as a requirements.txt body, controlled by `opts`.
///
/// Output is deterministic: packages sorted by their PEP 503-normalized name,
/// hash lines stable, no trailing whitespace, single trailing newline.
pub fn export_requirements_txt(lockfile: &Lockfile, opts: &ExportOptions) -> String {
    let exclusions = build_exclusion_set(&opts.exclude_packages);
    let mut packages: Vec<&Package> = lockfile
        .packages
        .iter()
        .filter(|p| !exclusions.contains(&pep503_normalize(&p.name)))
        .collect();
    packages.sort_by(|a, b| pep503_normalize(&a.name).cmp(&pep503_normalize(&b.name)));

    let reverse_deps = if opts.annotate {
        build_reverse_deps(lockfile)
    } else {
        BTreeMap::new()
    };

    let mut out = String::new();
    if opts.include_header {
        out.push_str(HEADER);
        out.push('\n');
    }

    for pkg in packages {
        render_one(&mut out, pkg, opts, &reverse_deps);
    }

    out
}

/// Compute the reverse-dependency adjacency from a lockfile: for each
/// package P, which other packages list P in their `dependencies` vec.
/// Keyed and matched on PEP 503-normalized names; values preserve the
/// original casing for display.
fn build_reverse_deps(lockfile: &Lockfile) -> BTreeMap<String, Vec<String>> {
    let mut adj: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for parent in &lockfile.packages {
        for dep in &parent.dependencies {
            let dep_key = pep503_normalize(dependency_name(dep));
            adj.entry(dep_key).or_default().push(parent.name.clone());
        }
    }
    for parents in adj.values_mut() {
        parents.sort_by_key(|a| pep503_normalize(a));
        parents.dedup_by(|a, b| pep503_normalize(a) == pep503_normalize(b));
    }
    adj
}

/// PEP 508 representation of a single lockfile package (the same surface
/// `export_requirements_txt` emits per line). Public so callers can do
/// per-package work without re-walking the full lockfile.
pub fn render_requirement_line(pkg: &Package, marker: Option<&str>) -> String {
    let mut buf = String::new();
    write_pep508_head(&mut buf, pkg);
    if let Some(m) = marker {
        let trimmed = m.trim();
        if !trimmed.is_empty() {
            buf.push_str(" ; ");
            buf.push_str(trimmed);
        }
    }
    if let Some(m) = &pkg.markers {
        let trimmed = m.trim();
        if !trimmed.is_empty() {
            buf.push_str(if marker.is_some() { " and " } else { " ; " });
            buf.push_str(trimmed);
        }
    }
    buf
}

fn render_one(
    out: &mut String,
    pkg: &Package,
    opts: &ExportOptions,
    reverse_deps: &BTreeMap<String, Vec<String>>,
) {
    let line = render_requirement_line(pkg, opts.global_marker.as_deref());
    if opts.include_hashes && !pkg.sha256.is_empty() && is_registry(pkg) {
        // Continuation form: `name==version \` then indented hash on next line.
        out.push_str(&line);
        out.push_str(" \\\n");
        out.push_str("    --hash=sha256:");
        out.push_str(strip_sha256_prefix(&pkg.sha256));
        out.push('\n');
    } else {
        out.push_str(&line);
        out.push('\n');
    }
    if opts.annotate {
        if let Some(parents) = reverse_deps.get(&pep503_normalize(&pkg.name)) {
            if !parents.is_empty() {
                out.push_str("    # via ");
                let joined = parents.join(", ");
                out.push_str(&joined);
                out.push('\n');
            }
        }
    }
}

fn write_pep508_head(out: &mut String, pkg: &Package) {
    match pkg.source_ref.as_ref().map(|s| s.kind) {
        Some(SourceRefKind::Git) => {
            out.push_str(&pkg.name);
            out.push_str(" @ git+");
            if let Some(url) = pkg.source_ref.as_ref().and_then(|s| s.url.as_deref()) {
                out.push_str(url);
            }
            if let Some(rev) = pkg.source_ref.as_ref().and_then(|s| s.rev.as_deref()) {
                if !rev.is_empty() {
                    out.push('@');
                    out.push_str(rev);
                }
            }
        }
        Some(SourceRefKind::Path) => {
            out.push_str(&pkg.name);
            out.push_str(" @ file://");
            if let Some(p) = pkg.source_ref.as_ref().and_then(|s| s.path.as_deref()) {
                out.push_str(p);
            }
        }
        // Registry or no source_ref — fall back to plain `name==version` pin.
        _ => {
            out.push_str(&pkg.name);
            out.push_str("==");
            out.push_str(&pkg.version);
        }
    }
}

fn is_registry(pkg: &Package) -> bool {
    matches!(
        pkg.source_ref.as_ref().map(|s| s.kind),
        Some(SourceRefKind::Registry) | None
    )
}

fn strip_sha256_prefix(s: &str) -> &str {
    s.strip_prefix("sha256:").unwrap_or(s)
}

fn build_exclusion_set(names: &[String]) -> std::collections::BTreeSet<String> {
    names.iter().map(|n| pep503_normalize(n)).collect()
}

fn dependency_name(spec: &str) -> &str {
    let trimmed = spec.trim();
    let head = trimmed
        .split_once(';')
        .map(|(name, _)| name)
        .unwrap_or(trimmed)
        .trim();
    let end = head
        .char_indices()
        .find_map(|(idx, ch)| {
            if matches!(ch, '<' | '>' | '=' | '!' | '~') || ch.is_whitespace() || ch == '[' {
                Some(idx)
            } else {
                None
            }
        })
        .unwrap_or(head.len());
    head[..end].trim()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pkgmanage::pkgmgr::lockfile::{Package, SourceRef};

    fn pkg(name: &str, version: &str, sha: &str) -> Package {
        Package {
            name: name.into(),
            version: version.into(),
            sha256: sha.into(),
            source: "https://pypi.org/simple".into(),
            dependencies: Vec::new(),
            markers: None,
            source_ref: None,
        }
    }

    fn lock(packages: Vec<Package>) -> Lockfile {
        Lockfile {
            format_version: 1,
            input_hash: "deadbeef".into(),
            packages,
        }
    }

    #[test]
    fn defaults_emit_header_and_hashes() {
        let l = lock(vec![pkg("requests", "2.31.0", "abc123")]);
        let body = export_requirements_txt(&l, &ExportOptions::default());
        assert!(body.starts_with("# This file was autogenerated"));
        assert!(body.contains("requests==2.31.0 \\"));
        assert!(body.contains("--hash=sha256:abc123"));
    }

    #[test]
    fn no_header_when_disabled() {
        let l = lock(vec![pkg("requests", "2.31.0", "abc123")]);
        let opts = ExportOptions {
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(!body.contains("autogenerated"));
        assert!(body.starts_with("requests==2.31.0"));
    }

    #[test]
    fn no_hashes_when_disabled() {
        let l = lock(vec![pkg("requests", "2.31.0", "abc123")]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(!body.contains("--hash"));
        assert_eq!(body, "requests==2.31.0\n");
    }

    #[test]
    fn output_is_alphabetical_by_normalized_name() {
        let l = lock(vec![
            pkg("Zed", "1", ""),
            pkg("alpha", "1", ""),
            pkg("My_Lib.X", "1", ""),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        let lines: Vec<&str> = body.lines().collect();
        // alpha < my-lib-x < zed
        assert_eq!(lines, vec!["alpha==1", "My_Lib.X==1", "Zed==1"]);
    }

    #[test]
    fn output_is_deterministic_across_runs() {
        let l = lock(vec![
            pkg("b", "1", "h1"),
            pkg("a", "1", "h2"),
            pkg("c", "1", "h3"),
        ]);
        let opts = ExportOptions::default();
        let body1 = export_requirements_txt(&l, &opts);
        let body2 = export_requirements_txt(&l, &opts);
        assert_eq!(body1, body2);
    }

    #[test]
    fn exclude_packages_filters_normalized_match() {
        let l = lock(vec![pkg("My-Pkg", "1", ""), pkg("keepit", "2", "")]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            // PEP 503: `My-Pkg` and `my_pkg` both normalize to `my-pkg`.
            exclude_packages: vec!["my_pkg".into()],
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(!body.contains("My-Pkg"));
        assert!(body.contains("keepit==2"));
    }

    #[test]
    fn git_source_renders_as_direct_url() {
        let mut p = pkg("requests", "2.31.0", "abc");
        p.source_ref = Some(SourceRef {
            kind: SourceRefKind::Git,
            path: None,
            url: Some("https://github.com/psf/requests".into()),
            rev: Some("v2.31.0".into()),
        });
        let l = lock(vec![p]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert_eq!(
            body.trim(),
            "requests @ git+https://github.com/psf/requests@v2.31.0"
        );
    }

    #[test]
    fn git_source_without_rev_omits_at_suffix() {
        let mut p = pkg("requests", "2.31.0", "");
        p.source_ref = Some(SourceRef {
            kind: SourceRefKind::Git,
            path: None,
            url: Some("https://github.com/psf/requests".into()),
            rev: None,
        });
        let l = lock(vec![p]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert_eq!(
            body.trim(),
            "requests @ git+https://github.com/psf/requests"
        );
    }

    #[test]
    fn path_source_renders_as_file_url() {
        let mut p = pkg("local-pkg", "0.0.1", "");
        p.source_ref = Some(SourceRef {
            kind: SourceRefKind::Path,
            path: Some("/abs/path/to/pkg".into()),
            url: None,
            rev: None,
        });
        let l = lock(vec![p]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert_eq!(body.trim(), "local-pkg @ file:///abs/path/to/pkg");
    }

    #[test]
    fn direct_urls_skip_hash_emission_even_when_enabled() {
        let mut p = pkg("requests", "2.31.0", "abc");
        p.source_ref = Some(SourceRef {
            kind: SourceRefKind::Git,
            path: None,
            url: Some("https://github.com/psf/requests".into()),
            rev: Some("v2.31.0".into()),
        });
        let l = lock(vec![p]);
        let body = export_requirements_txt(
            &l,
            &ExportOptions {
                include_header: false,
                ..Default::default()
            },
        );
        // requirements.txt cannot meaningfully `--hash` a git URL; suppress.
        assert!(!body.contains("--hash"));
    }

    #[test]
    fn sha256_with_prefix_is_stripped_in_output() {
        let l = lock(vec![pkg("requests", "2.31.0", "sha256:deadbeef")]);
        let body = export_requirements_txt(
            &l,
            &ExportOptions {
                include_header: false,
                ..Default::default()
            },
        );
        assert!(body.contains("--hash=sha256:deadbeef"));
        // Must not double up the prefix.
        assert!(!body.contains("sha256:sha256:"));
    }

    #[test]
    fn package_marker_is_emitted() {
        let mut p = pkg("requests", "2.31.0", "");
        p.markers = Some("python_version >= \"3.10\"".into());
        let l = lock(vec![p]);
        let body = export_requirements_txt(
            &l,
            &ExportOptions {
                include_hashes: false,
                include_header: false,
                ..Default::default()
            },
        );
        assert_eq!(body.trim(), "requests==2.31.0 ; python_version >= \"3.10\"");
    }

    #[test]
    fn global_marker_is_combined_with_package_marker() {
        let mut p = pkg("requests", "2.31.0", "");
        p.markers = Some("python_version >= \"3.10\"".into());
        let l = lock(vec![p]);
        let body = export_requirements_txt(
            &l,
            &ExportOptions {
                include_hashes: false,
                include_header: false,
                global_marker: Some("sys_platform == \"linux\"".into()),
                ..Default::default()
            },
        );
        assert_eq!(
            body.trim(),
            "requests==2.31.0 ; sys_platform == \"linux\" and python_version >= \"3.10\""
        );
    }

    #[test]
    fn global_marker_alone_uses_semicolon() {
        let p = pkg("requests", "2.31.0", "");
        let l = lock(vec![p]);
        let body = export_requirements_txt(
            &l,
            &ExportOptions {
                include_hashes: false,
                include_header: false,
                global_marker: Some("python_version >= \"3.10\"".into()),
                ..Default::default()
            },
        );
        assert_eq!(body.trim(), "requests==2.31.0 ; python_version >= \"3.10\"");
    }

    #[test]
    fn empty_lockfile_yields_only_header_or_empty() {
        let l = lock(Vec::new());
        let body_with_header = export_requirements_txt(&l, &ExportOptions::default());
        assert!(body_with_header.contains("autogenerated"));
        let body_blank = export_requirements_txt(
            &l,
            &ExportOptions {
                include_header: false,
                include_hashes: false,
                ..Default::default()
            },
        );
        assert_eq!(body_blank, "");
    }

    #[test]
    fn render_requirement_line_handles_no_markers() {
        let p = pkg("flask", "3.0.0", "");
        assert_eq!(render_requirement_line(&p, None), "flask==3.0.0");
    }

    #[test]
    fn pep503_normalize_helper_handles_mixed_separators() {
        assert_eq!(pep503_normalize("My_Pkg.X"), "my-pkg-x");
        assert_eq!(
            pep503_normalize("--leading--trailing--"),
            "leading-trailing"
        );
        assert_eq!(pep503_normalize("A...B"), "a-b");
    }

    #[test]
    fn output_ends_with_single_newline() {
        let l = lock(vec![pkg("a", "1", "")]);
        let body = export_requirements_txt(
            &l,
            &ExportOptions {
                include_hashes: false,
                include_header: false,
                ..Default::default()
            },
        );
        assert!(body.ends_with('\n'));
        assert!(!body.ends_with("\n\n"));
    }

    fn pkg_with_deps(name: &str, version: &str, deps: &[&str]) -> Package {
        let mut p = pkg(name, version, "");
        p.dependencies = deps.iter().map(|d| (*d).to_string()).collect();
        p
    }

    #[test]
    fn annotate_off_by_default_emits_no_via_lines() {
        let l = lock(vec![
            pkg_with_deps("app", "1", &["lib-a"]),
            pkg_with_deps("lib-a", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(!body.contains("# via"));
    }

    #[test]
    fn annotate_emits_via_line_for_consumer() {
        let l = lock(vec![
            pkg_with_deps("app", "1", &["lib-a"]),
            pkg_with_deps("lib-a", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert_eq!(body, "app==1\nlib-a==1\n    # via app\n");
    }

    #[test]
    fn annotate_skips_roots_with_no_reverse_deps() {
        let l = lock(vec![
            pkg_with_deps("root", "1", &["leaf"]),
            pkg_with_deps("leaf", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        let lines: Vec<&str> = body.lines().collect();
        // `root` is a root: no `# via` after it. `leaf` has `# via root`.
        assert_eq!(lines, vec!["leaf==1", "    # via root", "root==1"]);
    }

    #[test]
    fn annotate_lists_multiple_parents_comma_separated_pep503_sorted() {
        let l = lock(vec![
            pkg_with_deps("Zed", "1", &["common"]),
            pkg_with_deps("alpha", "1", &["common"]),
            pkg_with_deps("My_Lib.X", "1", &["common"]),
            pkg_with_deps("common", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        // Parents sorted by PEP 503 normalized name: alpha < my-lib-x < zed.
        // Display preserves original casing.
        assert!(body.contains("    # via alpha, My_Lib.X, Zed\n"));
    }

    #[test]
    fn annotate_dedupes_duplicate_parents() {
        // A single parent listing the dep twice (defensive — lockfiles
        // should normally dedupe upstream) must collapse to one entry.
        let l = lock(vec![
            pkg_with_deps("dup-parent", "1", &["shared", "shared"]),
            pkg_with_deps("shared", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(body.contains("    # via dup-parent\n"));
        assert!(!body.contains("# via dup-parent, dup-parent"));
    }

    #[test]
    fn annotate_matches_parents_via_pep503_normalization() {
        // Parent declares dependency as `My_Pkg.X` (non-normalized);
        // child appears as `my-pkg-x`. Must still be linked.
        let l = lock(vec![
            pkg_with_deps("consumer", "1", &["My_Pkg.X"]),
            pkg_with_deps("my-pkg-x", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(body.contains("my-pkg-x==1\n    # via consumer\n"));
    }

    #[test]
    fn annotate_matches_version_pinned_dependency_specs() {
        let l = lock(vec![
            pkg_with_deps("consumer", "1", &["child==2.0"]),
            pkg_with_deps("child", "2.0", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        assert!(body.contains("child==2.0\n    # via consumer\n"));
    }

    #[test]
    fn annotate_works_alongside_include_hashes() {
        let l = lock(vec![pkg_with_deps("app", "1", &["lib"]), {
            let mut p = pkg_with_deps("lib", "1", &[]);
            p.sha256 = "deadbeef".into();
            p
        }]);
        let opts = ExportOptions {
            include_hashes: true,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body = export_requirements_txt(&l, &opts);
        // Annotation must follow the hash continuation block, not interleave with it.
        let expected = "app==1\nlib==1 \\\n    --hash=sha256:deadbeef\n    # via app\n";
        assert_eq!(body, expected);
    }

    #[test]
    fn annotate_is_deterministic_across_runs() {
        let l = lock(vec![
            pkg_with_deps("b", "1", &["shared"]),
            pkg_with_deps("a", "1", &["shared"]),
            pkg_with_deps("shared", "1", &[]),
        ]);
        let opts = ExportOptions {
            include_hashes: false,
            include_header: false,
            annotate: true,
            ..Default::default()
        };
        let body1 = export_requirements_txt(&l, &opts);
        let body2 = export_requirements_txt(&l, &opts);
        assert_eq!(body1, body2);
    }
}
