#!/usr/bin/env python3.12
"""Shared PEP-723 `[tool.mamba]` fixture-header schema — ONE source of truth.

Before this module the header was generated by five hardcoded f-strings (one per
wall generator) and scraped independently by every reader. The schema (field
order, quoting, the fixed `# /// script` preamble, the trailing `# mamba-*`
markers) lived implicitly in all of those copies, so a change had to be made — by
hand and identically — in ~10 places. This consolidates GENERATION and PARSING so
they share one schema:

  * `PEP723Header` — the typed `[tool.mamba]` block + optional trailing markers.
  * `PEP723Header.render()` — emits the EXACT header bytes the generators emit
    today (the `# /// script` … `# ///` block, then `# mamba-xfail: …`, then an
    optional `# mamba-strict-type: …`). Generators concatenate their body onto it.
  * `parse_header(path)` — reads the `[tool.mamba]` block of a fixture back into a
    plain dict (the same scrape coverage_matrix.py / gen_goldens.py / keep_status.py
    / the batch drivers each open-coded).

This is a pure CONSOLIDATION: `render()` is byte-identical to the pre-refactor
f-strings, and `parse_header()` is a drop-in for the prior per-tool scrapers.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

# The fixed PEP-723 preamble every mamba fixture opens with, verbatim.
_PREAMBLE = (
    "# /// script\n"
    '# requires-python = ">=3.12"\n'
    "# dependencies = []\n"
    "#\n"
    "# [tool.mamba]\n"
)

# The `[tool.mamba]` fields, in the exact emission order all five generators use.
FIELD_ORDER = (
    "bucket", "lib", "dimension", "case", "subject", "kind",
    "xfail", "mem_carveout", "source", "status",
)

# Matches a `# key = "value"` line inside the `[tool.mamba]` block. Mirrors the
# regex coverage_matrix.py used (`^#\s*(\w+)\s*=\s*"(.*)"\s*$`).
_META_RE = re.compile(r'^#\s*(\w+)\s*=\s*"(.*)"\s*$')


@dataclass
class PEP723Header:
    """The `[tool.mamba]` fixture header.

    The ten `[tool.mamba]` fields are emitted in `FIELD_ORDER`. `xfail` is also
    echoed as the `# mamba-xfail:` marker line (every generator does this).
    `strict_type` (only the ① Type wall sets it) adds a `# mamba-strict-type:`
    marker line after it.
    """

    bucket: str
    lib: str
    dimension: str
    case: str
    subject: str
    kind: str
    xfail: str
    source: str
    mem_carveout: str = ""
    status: str = "filled"
    strict_type: str | None = None

    def render(self) -> str:
        """Return the EXACT header bytes (preamble + block + trailing markers).

        Ends with a trailing newline after the last `# mamba-*` marker line; the
        caller concatenates the fixture body directly onto it. Byte-identical to
        the pre-consolidation per-generator f-strings."""
        lines = [_PREAMBLE.rstrip("\n")]
        for field in FIELD_ORDER:
            lines.append(f'# {field} = "{getattr(self, field)}"')
        lines.append("# ///")
        lines.append(f"# mamba-xfail: {self.xfail}")
        if self.strict_type is not None:
            lines.append(f"# mamba-strict-type: {self.strict_type}")
        return "\n".join(lines) + "\n"


def parse_header(path: Path | str) -> dict:
    """Read a fixture's PEP-723 `[tool.mamba]` block back into a plain dict.

    Returns `{field: value}` for every `# key = "value"` line inside the
    `[tool.mamba]` block (only — the `# /// script` preamble keys above it and the
    trailing `# mamba-*` markers below it are not block fields). A drop-in for the
    per-tool scrapers (coverage_matrix.parse_meta, gen_goldens/keep_status
    parse_case, the `# subject =` line readers). Missing/unreadable file -> {}."""
    meta: dict = {}
    inblock = False
    try:
        with Path(path).open("r", encoding="utf-8", errors="replace") as fh:
            for i, line in enumerate(fh):
                if i > 60:
                    break
                s = line.strip()
                if s.startswith("# [tool.mamba]"):
                    inblock = True
                    continue
                if inblock and s.startswith("# ///"):
                    break
                if inblock:
                    m = _META_RE.match(s)
                    if m:
                        meta[m.group(1)] = m.group(2)
    except OSError:
        pass
    return meta
