// SPEC-MANAGED: .aw/tech-design/projects/jet/interfaces/cli/openapi-client-codegen-types-fetch-client-react-query-hooks.md#logic
// HANDWRITE-BEGIN
//! Emits `types.ts`: named interfaces and type aliases for component schemas.

use crate::codegen::names::{self, to_pascal};
use crate::codegen::openapi::{AdditionalProperties, RefOr, Schema, Spec};
use crate::codegen::tsmap::{type_expr, TypeMap};

pub const HEADER: &str = "// Code generated by jet codegen openapi. DO NOT EDIT.\n\n";

/// Render `types.ts` from `components.schemas`.
///
/// @spec .aw/tech-design/projects/jet/interfaces/cli/openapi-client-codegen-types-fetch-client-react-query-hooks.md#logic
pub fn emit(spec: &Spec, tm: &TypeMap) -> String {
    let mut out = String::from(HEADER);
    for (key, node) in &spec.components.schemas {
        let name = tm.names.get(key).cloned().unwrap_or_else(|| to_pascal(key));
        match node {
            RefOr::Ref(r) => {
                let target = tm
                    .resolve_ref(&r.reference)
                    .unwrap_or_else(|| "unknown".to_string());
                out.push_str(&format!("export type {name} = {target};\n\n"));
            }
            RefOr::Item(schema) => {
                if is_named_object(schema) {
                    out.push_str(&emit_interface(&name, schema, tm));
                } else {
                    out.push_str(&format!(
                        "export type {name} = {};\n\n",
                        type_expr(node, tm)
                    ));
                }
            }
        }
    }
    out
}

/// An object schema worth emitting as an `interface` (not a union/enum/alias).
fn is_named_object(schema: &Schema) -> bool {
    schema.one_of.is_empty()
        && schema.any_of.is_empty()
        && schema.all_of.is_empty()
        && schema.enum_values.is_empty()
        && (schema.type_names().iter().any(|t| t == "object") || !schema.properties.is_empty())
}

fn emit_interface(name: &str, schema: &Schema, tm: &TypeMap) -> String {
    let mut out = format!("export interface {name} {{\n");
    for (key, prop) in &schema.properties {
        let optional = !schema.required.iter().any(|r| r == key);
        out.push_str(&format!(
            "  {}{}: {};\n",
            names::prop_key(key),
            if optional { "?" } else { "" },
            type_expr(prop, tm)
        ));
    }
    match &schema.additional_properties {
        Some(AdditionalProperties::Bool(true)) => out.push_str("  [key: string]: unknown;\n"),
        Some(AdditionalProperties::Schema(s)) => {
            out.push_str(&format!("  [key: string]: {};\n", type_expr(s, tm)));
        }
        _ => {}
    }
    out.push_str("}\n\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::build_type_map;

    fn spec(json: &str) -> Spec {
        serde_json::from_str(json).unwrap()
    }

    #[test]
    fn emits_interface_with_optional_and_required() {
        let s = spec(
            r##"{"components":{"schemas":{"Pet":{"type":"object",
            "properties":{"id":{"type":"integer"},"name":{"type":"string"},"tag":{"type":"string"}},
            "required":["id","name"]}}}}"##,
        );
        let tm = build_type_map(&s);
        let out = emit(&s, &tm);
        assert!(out.contains("export interface Pet {"));
        assert!(out.contains("  id: number;"));
        assert!(out.contains("  name: string;"));
        assert!(out.contains("  tag?: string;"));
    }

    #[test]
    fn emits_type_alias_for_enum_and_union() {
        let s = spec(
            r##"{"components":{"schemas":{
            "Status":{"type":"string","enum":["open","closed"]},
            "Id":{"oneOf":[{"type":"string"},{"type":"integer"}]}}}}"##,
        );
        let tm = build_type_map(&s);
        let out = emit(&s, &tm);
        assert!(out.contains("export type Status = \"open\" | \"closed\";"));
        assert!(out.contains("export type Id = string | number;"));
    }
}
// HANDWRITE-END
