"""Retire synthetic claim-closure EC projections.

Capability claims are proven by real native Python EC cases or by colocated
Rust invariants run as a separate gate.  Generated cases that only compare
their own inventory metadata are not external contracts and must not reappear.
"""

from __future__ import annotations

import argparse
import json
import tomllib
from pathlib import Path
from typing import Any


EC_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = Path(__file__).resolve().parents[4]
PYPROJECT_PATH = EC_ROOT / "pyproject.toml"
CASE_ROOT = EC_ROOT / "src" / "cases"
BLOCK_START = "# aw:claim-reconciliation:start"
BLOCK_END = "# aw:claim-reconciliation:end"
GENERATED_MARKER = (
    "# Generated by src/claim_reconciliation.py; semantic acceptance requires "
    "independent EC review."
)
CASE_ID_PREFIX = "claim-closure-"
MIGRATION_MANIFEST_PATH = Path(__file__).with_name(
    "migration_reconciliation_manifest.json"
)


def _rust_invariant_case_ids() -> set[str]:
    manifest = json.loads(MIGRATION_MANIFEST_PATH.read_text(encoding="utf-8"))
    return {
        str(case["id"])
        for cluster in manifest["clusters"]
        for case in cluster["cases"]
        if case["migration_status"] == "rust_invariant"
    }


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="remove the retired generated inventory block and owned modules",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="verify the projection guard (the full EC runner is a separate gate)",
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=4,
        help="retained compatibility input; native EC concurrency belongs to aw ec verify",
    )
    return parser.parse_args()


def _inventory_document(text: str) -> dict[str, Any]:
    return tomllib.loads(text)


def _configured_cases(document: dict[str, Any]) -> list[dict[str, Any]]:
    cases = document["tool"]["aw"]["python-ec"]["cases"]
    if not isinstance(cases, list):
        raise RuntimeError("canonical Python EC cases must be an array")
    return cases


def _generated_block(text: str) -> str:
    if BLOCK_START not in text and BLOCK_END not in text:
        return ""
    if text.count(BLOCK_START) != 1 or text.count(BLOCK_END) != 1:
        raise RuntimeError("claim reconciliation markers must appear exactly once")
    start = text.index(BLOCK_START)
    end = text.index(BLOCK_END, start) + len(BLOCK_END)
    return text[start:end]


def _without_generated_block(text: str) -> str:
    block = _generated_block(text)
    if not block:
        return text
    return text.replace(block, "").rstrip() + "\n"


def _without_rust_invariant_cases(text: str) -> str:
    rust_invariant_case_ids = _rust_invariant_case_ids()
    header = "[[tool.aw.python-ec.cases]]"
    prefix, *blocks = text.split(header)
    kept = []
    for block in blocks:
        parsed = tomllib.loads(header + block)
        cases = parsed["tool"]["aw"]["python-ec"]["cases"]
        if len(cases) != 1:
            raise RuntimeError("one Python EC inventory block must contain one case")
        if str(cases[0].get("id", "")) not in rust_invariant_case_ids:
            kept.append(header + block)
    return prefix + "".join(kept)


def _owned_modules() -> tuple[Path, ...]:
    owned = []
    for path in CASE_ROOT.glob(f"{CASE_ID_PREFIX}*.py"):
        lines = path.read_text(encoding="utf-8").splitlines()
        if GENERATED_MARKER in lines:
            owned.append(path)
    return tuple(sorted(owned))


def _projection_findings(text: str) -> dict[str, list[str]]:
    rust_invariant_case_ids = _rust_invariant_case_ids()
    cases = _configured_cases(_inventory_document(text))
    return {
        "synthetic_claim_cases": sorted(
            str(case.get("id", ""))
            for case in cases
            if str(case.get("id", "")).startswith(CASE_ID_PREFIX)
        ),
        "cargo_delegating_commands": sorted(
            str(case.get("id", ""))
            for case in cases
            if "cargo test" in str(case.get("command", ""))
        ),
        "legacy_test_paths": sorted(
            str(case.get("id", ""))
            for case in cases
            if str(case.get("test_path", "")).startswith(
                "apps/agentic-workflow/tests/"
            )
            or str(case.get("test_path", "")).endswith(".rs")
        ),
        "rust_invariant_cases": sorted(
            str(case.get("id", ""))
            for case in cases
            if str(case.get("id", "")) in rust_invariant_case_ids
        ),
    }


def _result(text: str) -> dict[str, Any]:
    findings = _projection_findings(text)
    owned_modules = _owned_modules()
    generated_block = bool(_generated_block(text))
    clean = (
        not generated_block
        and not owned_modules
        and not any(findings.values())
    )
    case_count = len(_configured_cases(_inventory_document(text)))
    return {
        "schema_version": "aw.python-ec.claim-reconciliation.v2",
        "status": "clean" if clean else "drifted",
        "case_count": case_count,
        "synthetic_claim_case_count": len(findings["synthetic_claim_cases"]),
        "owned_synthetic_module_count": len(owned_modules),
        "cargo_delegating_command_count": len(findings["cargo_delegating_commands"]),
        "legacy_test_path_count": len(findings["legacy_test_paths"]),
        "rust_invariant_case_count": len(findings["rust_invariant_cases"]),
        "generated_inventory_block": generated_block,
        "findings": findings,
        "next": None
        if clean
        else (
            "python3 apps/agentic-workflow/external-contracts/src/"
            "claim_reconciliation.py --write"
        ),
    }


def main() -> int:
    args = _arguments()
    if args.jobs < 1:
        raise RuntimeError("--jobs must be at least 1")
    text = PYPROJECT_PATH.read_text(encoding="utf-8")
    if args.write:
        updated = _without_rust_invariant_cases(_without_generated_block(text))
        changed = updated != text
        if changed:
            PYPROJECT_PATH.write_text(updated, encoding="utf-8")
        removed_modules = 0
        for path in _owned_modules():
            path.unlink()
            removed_modules += 1
        removed_invariant_modules = 0
        for case_id in sorted(_rust_invariant_case_ids()):
            path = CASE_ROOT / f"{case_id}.py"
            if path.is_file():
                path.unlink()
                removed_invariant_modules += 1
        result = _result(updated)
        result["status"] = (
            "written"
            if changed or removed_modules or removed_invariant_modules
            else result["status"]
        )
        result["removed_synthetic_modules"] = removed_modules
        result["removed_rust_invariant_modules"] = removed_invariant_modules
        print(json.dumps(result, sort_keys=True))
        return 0 if not any(result["findings"].values()) else 1

    result = _result(text)
    print(json.dumps(result, sort_keys=True))
    return 0 if result["status"] == "clean" else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (KeyError, OSError, RuntimeError, tomllib.TOMLDecodeError) as error:
        print(f"claim reconciliation failed: {error}", file=__import__("sys").stderr)
        raise SystemExit(2) from error
