"""Retire synthetic claim-closure EC projections.

Capability claims are proven by real native Python EC cases or by colocated
Rust invariants run as a separate gate.  Generated cases that only compare
their own inventory metadata are not external contracts and must not reappear.
"""

from __future__ import annotations

import argparse
import json
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any


EC_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = Path(__file__).resolve().parents[4]
PYPROJECT_PATH = EC_ROOT / "pyproject.toml"
CASE_ROOT = EC_ROOT / "src" / "cases"
BLOCK_START = "# aw:claim-reconciliation:start"
BLOCK_END = "# aw:claim-reconciliation:end"
GENERATED_MARKER = (
    "# Generated by src/claim_reconciliation.py; semantic acceptance requires "
    "independent EC review."
)
CASE_ID_PREFIX = "claim-closure-"
MIGRATION_MANIFEST_PATH = Path(__file__).with_name(
    "migration_reconciliation_manifest.json"
)

_SCHEMA = "aw.python-ec.expected-mapping.v1"
_FIELDS = ("case_id", "capability_id", "use_case_id", "dimension")


@dataclass(frozen=True)
class _T:
    case_id: str
    capability_id: str
    use_case_id: str
    dimension: str

    def d(self) -> dict[str, str]:
        return {
            "case_id": self.case_id,
            "capability_id": self.capability_id,
            "use_case_id": self.use_case_id,
            "dimension": self.dimension,
        }


def _parse_toml(text: str) -> tuple[list[_T], list[str]]:
    try:
        cases = tomllib.loads(text)["tool"]["aw"]["python-ec"]["cases"]
        if not isinstance(cases, list):
            raise TypeError("cases must be a list")
    except Exception as exc:  # noqa: BLE001
        return [], [f"malformed candidate TOML: {exc}"]
    out, errs = [], []
    for i, c in enumerate(cases):
        if not isinstance(c, dict):
            errs.append(f"case[{i}] must be an object")
            continue
        row = {
            "case_id": c.get("id", ""),
            "capability_id": c.get("capability_id", ""),
            "use_case_id": c.get("use_case_id", ""),
            "dimension": c.get("dimension", ""),
        }
        bad = [f for f in _FIELDS if not isinstance(row[f], str) or not row[f].strip()]
        if bad:
            errs += [f"case[{i}] empty field '{f}'" for f in bad]
            continue
        out.append(_T(**{f: str(row[f]) for f in _FIELDS}))
    return ([], errs) if errs else (out, [])


def _parse_json(text: str) -> tuple[list[_T], list[str]]:
    try:
        doc = json.loads(text)
        if not isinstance(doc, dict) or doc.get("schema_version") != _SCHEMA:
            raise ValueError(f"schema_version must be '{_SCHEMA}'")
        entries = doc.get("mappings")
        if not isinstance(entries, list):
            raise TypeError("mappings must be a list")
    except Exception as exc:  # noqa: BLE001
        return [], [f"malformed expected mapping JSON: {exc}"]
    out, errs = [], []
    for i, e in enumerate(entries):
        if not isinstance(e, dict):
            errs.append(f"expected[{i}] must be an object")
            continue
        bad = [
            f
            for f in _FIELDS
            if not isinstance(e.get(f, ""), str) or not str(e.get(f, "")).strip()
        ]
        if bad:
            errs += [f"expected[{i}] empty field '{f}'" for f in bad]
            continue
        out.append(_T(**{f: str(e[f]) for f in _FIELDS}))
    return ([], errs) if errs else (out, [])


def _by_case_id(d: dict[str, str]) -> str:
    return d["case_id"]


def reconcile_copied_inventory(
    candidate_toml: str, expected_mapping_json: str
) -> dict[str, Any]:
    """Read-only comparison of a copied candidate inventory against an independent
    exact mapping. Never mutates either input. No I/O."""
    cand, ce = _parse_toml(candidate_toml)
    exp, ee = _parse_json(expected_mapping_json)
    errs = ce + ee
    _empty: list[Any] = []
    if errs:
        return {
            "schema_version": _SCHEMA,
            "status": "drifted",
            "case_count": 0,
            "case_mapping": _empty,
            "findings": {
                "missing_expected_mappings": _empty,
                "unexpected_mappings": _empty,
                "duplicate_case_ids": _empty,
                "malformed_inputs": sorted(errs),
                "binding_mismatches": _empty,
            },
        }
    counts: dict[str, int] = {}
    for t in cand:
        counts[t.case_id] = counts.get(t.case_id, 0) + 1
    dups = sorted(k for k, v in counts.items() if v > 1)
    cs, es = set(cand), set(exp)
    missing = sorted((t.d() for t in es - cs), key=_by_case_id)
    unexpected = sorted((t.d() for t in cs - es), key=_by_case_id)
    uni_cand = {t.case_id: t for t in cand if counts[t.case_id] == 1}
    uni_exp = {t.case_id: t for t in exp}
    bmis = sorted(
        cid for cid in uni_cand if cid in uni_exp and uni_cand[cid] != uni_exp[cid]
    )
    mapping = sorted((t.d() for t in cand), key=_by_case_id)
    clean = not (missing or unexpected or dups or bmis)
    return {
        "schema_version": _SCHEMA,
        "status": "clean" if clean else "drifted",
        "case_count": len(cand),
        "case_mapping": mapping,
        "findings": {
            "missing_expected_mappings": missing,
            "unexpected_mappings": unexpected,
            "duplicate_case_ids": dups,
            "malformed_inputs": [],
            "binding_mismatches": bmis,
        },
    }


def _rust_invariant_case_ids() -> set[str]:
    manifest = json.loads(MIGRATION_MANIFEST_PATH.read_text(encoding="utf-8"))
    return {
        str(case["id"])
        for cluster in manifest["clusters"]
        for case in cluster["cases"]
        if case["migration_status"] == "rust_invariant"
    }


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--inventory",
        type=Path,
        default=None,
        help="path to copied candidate pyproject.toml inventory",
    )
    parser.add_argument(
        "--expected-mapping",
        type=Path,
        default=None,
        help="path to expected mappings json document",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="remove the retired generated inventory block and owned modules",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="verify the projection guard (the full EC runner is a separate gate)",
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=4,
        help="retained compatibility input; native EC concurrency belongs to aw ec verify",
    )
    return parser.parse_args()


def _inventory_document(text: str) -> dict[str, Any]:
    return tomllib.loads(text)


def _configured_cases(document: dict[str, Any]) -> list[dict[str, Any]]:
    cases = document["tool"]["aw"]["python-ec"]["cases"]
    if not isinstance(cases, list):
        raise RuntimeError("canonical Python EC cases must be an array")
    return cases


def _generated_block(text: str) -> str:
    if BLOCK_START not in text and BLOCK_END not in text:
        return ""
    if text.count(BLOCK_START) != 1 or text.count(BLOCK_END) != 1:
        raise RuntimeError("claim reconciliation markers must appear exactly once")
    start = text.index(BLOCK_START)
    end = text.index(BLOCK_END, start) + len(BLOCK_END)
    return text[start:end]


def _without_generated_block(text: str) -> str:
    block = _generated_block(text)
    if not block:
        return text
    return text.replace(block, "").rstrip() + "\n"


def _without_rust_invariant_cases(text: str) -> str:
    rust_invariant_case_ids = _rust_invariant_case_ids()
    header = "[[tool.aw.python-ec.cases]]"
    prefix, *blocks = text.split(header)
    kept = []
    for block in blocks:
        parsed = tomllib.loads(header + block)
        cases = parsed["tool"]["aw"]["python-ec"]["cases"]
        if len(cases) != 1:
            raise RuntimeError("one Python EC inventory block must contain one case")
        if str(cases[0].get("id", "")) not in rust_invariant_case_ids:
            kept.append(header + block)
    return prefix + "".join(kept)


def _owned_modules() -> tuple[Path, ...]:
    owned = []
    for path in CASE_ROOT.glob(f"{CASE_ID_PREFIX}*.py"):
        lines = path.read_text(encoding="utf-8").splitlines()
        if GENERATED_MARKER in lines:
            owned.append(path)
    return tuple(sorted(owned))


def _projection_findings(text: str) -> dict[str, list[str]]:
    rust_invariant_case_ids = _rust_invariant_case_ids()
    cases = _configured_cases(_inventory_document(text))
    return {
        "synthetic_claim_cases": sorted(
            str(case.get("id", ""))
            for case in cases
            if str(case.get("id", "")).startswith(CASE_ID_PREFIX)
        ),
        "cargo_delegating_commands": sorted(
            str(case.get("id", ""))
            for case in cases
            if "cargo test" in str(case.get("command", ""))
        ),
        "legacy_test_paths": sorted(
            str(case.get("id", ""))
            for case in cases
            if str(case.get("test_path", "")).startswith(
                "apps/agentic-workflow/tests/"
            )
            or str(case.get("test_path", "")).endswith(".rs")
        ),
        "rust_invariant_cases": sorted(
            str(case.get("id", ""))
            for case in cases
            if str(case.get("id", "")) in rust_invariant_case_ids
        ),
    }


def _result(text: str) -> dict[str, Any]:
    findings = _projection_findings(text)
    owned_modules = _owned_modules()
    generated_block = bool(_generated_block(text))
    clean = (
        not generated_block
        and not owned_modules
        and not findings["synthetic_claim_cases"]
        and not findings["cargo_delegating_commands"]
        and not findings["legacy_test_paths"]
    )
    case_count = len(_configured_cases(_inventory_document(text)))
    return {
        "schema_version": "aw.python-ec.claim-reconciliation.v2",
        "status": "clean" if clean else "drifted",
        "case_count": case_count,
        "synthetic_claim_case_count": len(findings["synthetic_claim_cases"]),
        "owned_synthetic_module_count": len(owned_modules),
        "cargo_delegating_command_count": len(findings["cargo_delegating_commands"]),
        "legacy_test_path_count": len(findings["legacy_test_paths"]),
        "rust_invariant_case_count": len(findings["rust_invariant_cases"]),
        "generated_inventory_block": generated_block,
        "findings": findings,
        "next": None
        if clean
        else (
            "python3 apps/agentic-workflow/external-contracts/src/"
            "claim_reconciliation.py --write"
        ),
    }


def main() -> int:
    args = _arguments()
    if (args.inventory is None) != (args.expected_mapping is None):
        print(
            "claim reconciliation failed: both --inventory and --expected-mapping must be provided together",
            file=__import__("sys").stderr,
        )
        raise SystemExit(2)

    if args.inventory is not None and args.expected_mapping is not None:
        candidate_toml = args.inventory.read_text(encoding="utf-8")
        expected_mapping_json = args.expected_mapping.read_text(encoding="utf-8")
        result = reconcile_copied_inventory(candidate_toml, expected_mapping_json)
        print(json.dumps(result, sort_keys=True))
        return 0 if result["status"] == "clean" else 1

    if args.jobs < 1:
        raise RuntimeError("--jobs must be at least 1")
    text = PYPROJECT_PATH.read_text(encoding="utf-8")
    if args.write:
        updated = _without_rust_invariant_cases(_without_generated_block(text))
        changed = updated != text
        if changed:
            PYPROJECT_PATH.write_text(updated, encoding="utf-8")
        removed_modules = 0
        for path in _owned_modules():
            path.unlink()
            removed_modules += 1
        removed_invariant_modules = 0
        for case_id in sorted(_rust_invariant_case_ids()):
            path = CASE_ROOT / f"{case_id}.py"
            if path.is_file():
                path.unlink()
                removed_invariant_modules += 1
        result = _result(updated)
        result["status"] = (
            "written"
            if changed or removed_modules or removed_invariant_modules
            else result["status"]
        )
        result["removed_synthetic_modules"] = removed_modules
        result["removed_rust_invariant_modules"] = removed_invariant_modules
        print(json.dumps(result, sort_keys=True))
        return 0 if not any(result["findings"].values()) else 1

    result = _result(text)
    print(json.dumps(result, sort_keys=True))
    return 0 if result["status"] == "clean" else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (KeyError, OSError, RuntimeError, tomllib.TOMLDecodeError) as error:
        print(f"claim reconciliation failed: {error}", file=__import__("sys").stderr)
        raise SystemExit(2) from error
