// <HANDWRITE gap="standardize:claim-code" tracker="projects-jet-tests-snapshots-codegen-minimal-hooks-ts" reason="Existing code claimed during Score standardization until deterministic generator coverage lands.">
// Code generated by jet codegen openapi. DO NOT EDIT.

import { useMutation, useQuery } from "@tanstack/react-query";
import type { UseMutationOptions, UseQueryOptions } from "@tanstack/react-query";
import type { ApiClient } from "./client";
import type { CreatePetData, CreatePetResponse, GetPetByIdData, GetPetByIdResponse, ListPetsData, ListPetsResponse } from "./types";

export function createHooks(client: ApiClient) {
  return {
    useListPetsQuery(data: ListPetsData, options?: Omit<UseQueryOptions<ListPetsResponse>, "queryKey" | "queryFn">) {
      return useQuery<ListPetsResponse>({ queryKey: ["listPets", data], queryFn: () => client.listPets(data), ...options });
    },
    useCreatePetMutation(options?: UseMutationOptions<CreatePetResponse, Error, CreatePetData>) {
      return useMutation<CreatePetResponse, Error, CreatePetData>({ mutationFn: (data) => client.createPet(data), ...options });
    },
    useGetPetByIdQuery(data: GetPetByIdData, options?: Omit<UseQueryOptions<GetPetByIdResponse>, "queryKey" | "queryFn">) {
      return useQuery<GetPetByIdResponse>({ queryKey: ["getPetById", data], queryFn: () => client.getPetById(data), ...options });
    },
  };
}

// </HANDWRITE>
