apiVersion: v1
kind: Service
metadata:
  name: relay-headless
  namespace: relay
  labels: {app: relay, role: server}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {app: relay, role: server}
  ports:
    - {name: http, port: 7000, targetPort: http, protocol: TCP}
    - {name: raft, port: 7001, targetPort: raft, protocol: TCP}
---
apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: relay
  labels: {app: relay, role: server}
spec:
  selector: {app: relay, role: server}
  ports:
    - {name: http, port: 7000, targetPort: http, protocol: TCP}
