from typing import Optional

class Jieba:
    def __init__(self) -> None: ...
    def cut(self, text: str) -> list[str]: ...
    def cut_all(self, text: str) -> list[str]: ...
    def cut_for_search(self, text: str) -> list[str]: ...
    def lcut(self, text: str) -> list[str]: ...
    def add_word(self, word: str, freq: int, tag: Optional[str] = None) -> None: ...
    def tag(self, text: str) -> list[tuple[str, str]]: ...
    def tokenize(self, text: str) -> list[tuple[str, int, int]]: ...
    def cut_batch(self, texts: list[str]) -> list[list[str]]: ...

class KeywordExtractor:
    def __init__(self) -> None: ...
    def extract(self, text: str, top_k: int) -> list[tuple[str, float]]: ...

class BM25Okapi:
    def __init__(self, corpus: list[list[str]], k1: float = 1.5, b: float = 0.75) -> None: ...
    def get_scores(self, query: list[str]) -> list[float]: ...
    def get_top_n(self, query: list[str], n: int) -> list[int]: ...
    def get_idf(self, term: str) -> Optional[float]: ...
    @property
    def corpus_size(self) -> int: ...
    @property
    def avgdl(self) -> float: ...
    def doc_lengths(self) -> list[int]: ...
    def add_document(self, doc: list[str]) -> None: ...
    def remove_document(self, idx: int) -> bool: ...

class TfIdf:
    def __init__(self, corpus: list[list[str]]) -> None: ...
    def get_scores(self, query: list[str]) -> list[float]: ...
    def get_top_n(self, query: list[str], n: int) -> list[int]: ...

class Document:
    @staticmethod
    def from_html(html: str) -> Document: ...
    @staticmethod
    def from_xml(xml: str) -> Document: ...
    @property
    def root(self) -> int: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def xpath(self, expr: str) -> list[Element]: ...
    def cssselect(self, selector: str) -> list[Element]: ...
    def find_by_tag(self, tag: str) -> list[Element]: ...
    def find_by_id(self, id: str) -> Optional[Element]: ...

class Element:
    pass

class DiffOp:
    @property
    def op_type(self) -> str: ...
    @property
    def text(self) -> Optional[str]: ...
    @property
    def old_text(self) -> Optional[str]: ...
    @property
    def new_text(self) -> Optional[str]: ...

class WordDiffOp:
    @property
    def op_type(self) -> str: ...
    @property
    def text(self) -> str: ...

class FuzzyMatch:
    @property
    def text(self) -> str: ...
    @property
    def score(self) -> float: ...
    @property
    def index(self) -> int: ...

class FuzzySearcher:
    def __init__(self, items: list[str], metric: str = "levenshtein", threshold: float = 0.6, prefix_weight: float = 0.1) -> None: ...
    def search(self, query: str) -> list[FuzzyMatch]: ...
    def search_top_n(self, query: str, n: int) -> list[FuzzyMatch]: ...
    def best_match(self, query: str) -> Optional[FuzzyMatch]: ...
    def add_item(self, item: str) -> None: ...

class TemplateEngine:
    def __init__(self) -> None: ...
    def add_template(self, name: str, source: str) -> None: ...
    def render(self, template: str, **kwargs: object) -> str: ...

class segment:
    Jieba = Jieba
    KeywordExtractor = KeywordExtractor

class rank:
    BM25Okapi = BM25Okapi
    TfIdf = TfIdf

class markup:
    Document = Document
    Element = Element
