// SPEC-MANAGED: generated by `aw ec gen` from EC claim `MAMBA-T1-FT-GATHER-EFFICIENCY` — fill the body.
// @ec mamba-t1-to-thread-gather-efficiency
// @capability mamba-core-semantics
#[test]
fn mamba_core_semantics_ec() {
    // contract: On a host exposing at least four logical CPUs, four equal CPU-bound asyncio.to_thread jobs complete with wall-clock speedup at least 1.50x versus the same jobs run serially, while returning the exact same ordered results.
    // contract: During the parallel phase, measured process CPU time divided by wall time is at least 1.50, proving concurrent work used more than one core rather than cooperative single-loop scheduling.
    // contract: Parallel peak RSS is no greater than 1.25 times serial peak RSS plus 16 MiB for the same workload; CPU scaling cannot be purchased with unbounded retained worker/future state.
    // contract: The gate records logical CPU count, serial and parallel wall time, process CPU time, peak RSS, result digest, and speedup; unsupported hosts are explicit evidence, never a silent pass.
    // fill: drive the in-process target and assert the contract above.
todo!("implement EC claim MAMBA-T1-FT-GATHER-EFFICIENCY");
}
